export { default as authRoutes } from './auth';
export { default as companiesRoutes } from './companies';
export { default as subsidiesRoutes } from './subsidies';
export { default as jobsRoutes } from './jobs';
export { default as internalRoutes } from './internal';
export { default as knowledgeRoutes } from './knowledge';
export { default as consumerRoutes } from './consumer';
export { default as kpiRoutes } from './kpi';
export { default as adminRoutes } from './admin';
export { default as profileRoutes } from './profile';
export { default as chatRoutes } from './chat';
export { default as draftRoutes } from './draft';
export { default as adminDashboardRoutes } from './admin-dashboard';
export { agencyRoutes } from './agency';
export { portalRoutes } from './portal';
export { default as cronRoutes } from './cron';
export { default as mastersRoutes } from './masters';
export { default as kouboMonitorRoutes } from './koubo-monitors';
