-- Generated seed for source_registry (secretariats)
-- Source: seeds/source_registry_secretariats.csv
-- Generated at: 2026-01-21T14:57:24.060Z

INSERT INTO source_registry (
  registry_id, scope, geo_id, program_key,
  root_url, domain_key, crawl_strategy, max_depth,
  target_types, keyword_filter, update_freq, enabled,
  robots_required, priority, notes,
  data_scope, authority, stop_condition,
  list_page_selector, pdf_keywords,
  last_hash, last_crawl_status,
  next_crawl_at, created_at, updated_at
) VALUES
(
  'sec-it-hojo',
  'national',
  NULL,
  'it-hojo',
  'https://www.it-hojo.jp/',
  'it-hojo.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'daily',
  1,
  1,
  1,
  'IT導入補助金 事務局（最重要）',
  'guideline,faq,forms,how_to_write,news',
  'official',
  'budget',
  'a[href$=''.pdf'']',
  '公募要領,募集要項,交付規程,申請マニュアル,手引き,FAQ,Q&A,様式,記入例,採択事例',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-monodukuri',
  'national',
  NULL,
  'monodukuri-hojo',
  'https://portal.monodukuri-hojo.jp/',
  'monodukuri-hojo.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'daily',
  1,
  1,
  1,
  'ものづくり補助金 事務局',
  'guideline,faq,forms,how_to_write,examples,news',
  'official',
  'budget',
  'a[href$=''.pdf'']',
  '公募要領,募集要項,申請の手引き,FAQ,Q&A,様式,記入例,採択結果,採択事例',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-jizokuka',
  'national',
  NULL,
  'jizokuka-hojo',
  'https://www.jizokuka-hojo.jp/',
  'jizokuka-hojo.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'daily',
  1,
  1,
  1,
  '小規模事業者持続化補助金 事務局',
  'guideline,faq,forms,how_to_write,news',
  'official',
  'budget',
  'a[href$=''.pdf'']',
  '公募要領,募集要項,申請手引き,FAQ,Q&A,様式,記入例',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-saikouchiku',
  'national',
  NULL,
  'saikouchiku',
  'https://jigyou-saikouchiku.go.jp/',
  'jigyou-saikouchiku.go.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'daily',
  1,
  1,
  2,
  '事業再構築補助金 事務局',
  'guideline,faq,forms,how_to_write,examples,news',
  'official',
  'deadline',
  'a[href$=''.pdf'']',
  '公募要領,募集要項,申請マニュアル,FAQ,Q&A,様式,記入例,採択結果',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-smrj',
  'national',
  NULL,
  'smrj-portal',
  'https://www.smrj.go.jp/',
  'smrj.go.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'weekly',
  1,
  1,
  3,
  '中小機構（公募/支援）ポータル',
  'news,guideline,faq',
  'official',
  'deadline',
  'a[href$=''.pdf'']',
  '補助金,助成金,公募,募集,支援,FAQ,Q&A,要領',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-chusho',
  'national',
  NULL,
  'chusho-meti',
  'https://www.chusho.meti.go.jp/',
  'chusho.meti.go.jp',
  'scrape',
  1,
  'html',
  '補助金',
  'weekly',
  1,
  1,
  3,
  '中小企業庁（公募/施策）- ブロックされやすい',
  'news,guideline',
  'official',
  'deadline',
  'a[href*=''pdf'']',
  '公募,募集,補助金,助成金,要領,FAQ,様式',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-mhlw',
  'national',
  NULL,
  'mhlw-subsidy',
  'https://www.mhlw.go.jp/',
  'mhlw.go.jp',
  'crawl',
  2,
  'html',
  '助成金',
  'weekly',
  1,
  1,
  3,
  '厚労省（雇用/助成金）',
  'guideline,faq,forms,news',
  'official',
  'deadline',
  'a[href$=''.pdf'']',
  '助成金,パンフレット,支給要領,申請書,様式,FAQ,Q&A',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-maff',
  'national',
  NULL,
  'maff-grants',
  'https://www.maff.go.jp/',
  'maff.go.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'weekly',
  1,
  1,
  4,
  '農水省（補助/支援）',
  'guideline,news',
  'official',
  'deadline',
  'a[href$=''.pdf'']',
  '補助,支援,公募,募集,要領,交付要綱',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
),
(
  'sec-jnet21',
  'national',
  NULL,
  'jnet21',
  'https://j-net21.smrj.go.jp/',
  'j-net21.smrj.go.jp',
  'crawl',
  2,
  'html',
  '補助金',
  'weekly',
  1,
  1,
  4,
  'J-Net21（横断ポータル）',
  'news,portal',
  'semi_official',
  'deadline',
  'a[href*=''pdf'']',
  '補助金,助成金,支援情報,公募,募集',
  NULL,
  NULL,
  datetime('now','-1 minute'),
  datetime('now'),
  datetime('now')
)
ON CONFLICT(registry_id) DO UPDATE SET
  scope = excluded.scope,
  geo_id = excluded.geo_id,
  program_key = excluded.program_key,
  root_url = excluded.root_url,
  domain_key = excluded.domain_key,
  crawl_strategy = excluded.crawl_strategy,
  max_depth = excluded.max_depth,
  target_types = excluded.target_types,
  keyword_filter = excluded.keyword_filter,
  update_freq = excluded.update_freq,
  enabled = excluded.enabled,
  robots_required = excluded.robots_required,
  priority = excluded.priority,
  notes = excluded.notes,
  data_scope = excluded.data_scope,
  authority = excluded.authority,
  stop_condition = excluded.stop_condition,
  list_page_selector = excluded.list_page_selector,
  pdf_keywords = excluded.pdf_keywords,
  updated_at = datetime('now');
