-- Phase 6b: Update remaining 4 subsidies from score 90 to 95

-- 1. CAREER-UP-SEISHAIN: キャリアアップ助成金 正社員化コース (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"キャリアアップ助成金（正社員化コース）令和7年度","version":"令和7年度","subsidy_overview":{"summary":"有期雇用労働者等を正社員に転換した場合に助成する制度。非正規雇用労働者のキャリアアップを促進","purpose":"非正規雇用労働者の正社員化促進・処遇改善"},"max_amount":"1人当たり最大80万円（40万円×2期）","subsidy_rate":"定額支給","support_amounts":{"重点支援対象者":{"有期→正社員_中小":"80万円（40万円×2期）","有期→正社員_大企業":"60万円（30万円×2期）","無期→正社員_中小":"40万円（20万円×2期）","無期→正社員_大企業":"30万円（15万円×2期）"},"通常":{"有期→正社員_中小":"40万円（20万円×2期）","有期→正社員_大企業":"30万円（15万円×2期）"}},"target_requirements":{"business_type":"雇用保険適用事業所の事業主","plan":"キャリアアップ計画を事前に提出（実施日前日まで）","wage":"正社員化後6か月の賃金が転換前6か月より3%以上増額","employment":"正社員化した日の6か月前から1年間に解雇等がないこと","duration":"有期雇用が6か月以上の労働者が対象"},"重点支援対象者":["雇入れから3年以上の有期雇用労働者","派遣労働者","母子家庭の母・父子家庭の父","人材開発支援助成金の訓練修了者"],"application_method":"管轄の労働局またはハローワークに支給申請書を提出（正社員化後6か月経過後2か月以内）","application_period":"通年申請可能","key_points":["キャリアアップ計画の事前提出が必須","正社員化後6か月の賃金3%以上増額が要件","重点支援対象者は助成額が倍増","1年度1事業所あたり20人まで"],"contact":"管轄の都道府県労働局またはハローワーク","official_url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html","pdf_source":"https://www.mhlw.go.jp/content/11910500/001512805.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'CAREER-UP-SEISHAIN';

-- 2. JINZAI-RESKILLING: 人材開発支援助成金 リスキリングコース (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"人材開発支援助成金（事業展開等リスキリング支援コース）令和7年度","version":"令和7年度","subsidy_overview":{"summary":"新規事業立ち上げやDX推進等に伴い、新たな分野で必要となる知識・技能を習得させるための訓練経費と賃金の一部を助成","purpose":"事業展開・DX・GXに伴うリスキリング支援"},"max_amount":"1事業所1年度あたり1億円","subsidy_rate":{"経費助成_中小":"75%","経費助成_大企業":"60%","賃金助成_中小":"1時間当たり1,000円","賃金助成_大企業":"1時間当たり500円"},"target_requirements":{"business_type":"雇用保険適用事業所の事業主","plan":"職業訓練実施計画を事前に提出","training":"新規事業立ち上げ、DX推進、GX推進等に伴う訓練","hours":"10時間以上の訓練（OFF-JT）","provider":"事業主以外の者が行う訓練"},"eligible_training":["新規事業のための専門知識訓練","DX推進のためのIT・デジタル訓練","GX推進のための脱炭素関連訓練","海外展開のための語学・貿易実務訓練"],"application_method":"管轄の労働局に計画届を提出→訓練実施→支給申請","application_period":"通年申請可能（計画届は訓練開始日の1か月前まで）","key_points":["経費助成率は中小企業75%と非常に高い","1事業所年間1億円の大きな助成枠","賃金助成もあり実質的な人件費サポート","eラーニング・通信制も対象","定額制サービスは1人1月2万円上限"],"contact":"管轄の都道府県労働局","official_url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/d01-1.html","pdf_source":"https://www.mhlw.go.jp/content/11800000/001514283.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'JINZAI-RESKILLING';

-- 3. JIZOKUKA-KYODO-02: 持続化補助金 共同・協業型 第2回 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"小規模事業者持続化補助金＜共同・協業型＞（第2回公募）","version":"第2回公募","subsidy_overview":{"summary":"地域振興等機関が中心となり、複数の小規模事業者の商品・サービスの改良やブランディング、販路開拓を一体的に支援する補助金","purpose":"複数小規模事業者の共同・協業による販路開拓支援"},"max_amount":"5,000万円（地域振興等機関+参加事業者の合計）","subsidy_rate":"2/3以内","target_requirements":{"applicant":"地域振興等機関（地域の商工団体、観光協会、NPO法人等）","participants":"複数の小規模事業者（商業・サービス5人以下、製造業等20人以下）","collaboration":"3者以上の小規模事業者が参加","area":"同一地域内での取組"},"eligible_expenses":["機械装置等費","広報費","ウェブサイト関連費","展示会等出展費","旅費","新商品開発費","借料","外注費","委託費"],"application_period":{"公募要領公開":"2025年12月23日","申請受付開始":"2026年1月16日","申請締切":"2026年2月27日"},"application_method":"jGrants電子申請（GビズIDプライムアカウント必須）","key_points":["地域振興等機関が主体・中心的役割を担う","3者以上の小規模事業者が共同参加","補助上限5,000万円と大型","令和7年度補正予算で第3回以降も予定"],"contact":"小規模事業者持続化補助金＜共同・協業型＞事務局","official_url":"https://r6.kyodokyogyohojokin.info/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_jizoku_kyodokyogyo.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'JIZOKUKA-KYODO-02';

-- 4. SHORYOKUKA-CATALOG: 省力化投資補助金 カタログ注文型 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業省力化投資補助金（カタログ注文型）","version":"2026年度","subsidy_overview":{"summary":"IoT・ロボット等の人手不足解消に効果がある汎用製品をカタログから選んで導入する中小企業を支援する補助金","purpose":"カタログ掲載製品の導入による人手不足解消・生産性向上"},"max_amount_by_size":{"5人以下":"200万円（賃上げ:300万円）","6〜20人":"500万円（賃上げ:750万円）","21人以上":"1,000万円（賃上げ:1,500万円）"},"subsidy_rate":"1/2","target_requirements":{"business_type":"中小企業・小規模事業者等","product":"カタログに掲載された省力化製品の導入","productivity":"労働生産性を年平均成長率4.0%以上向上させる計画","vendor":"カタログ掲載の販売事業者から購入"},"eligible_products":"IoT機器、ロボット、自動化設備等のカタログ掲載製品","application_method":"GビズIDプライムアカウントによる電子申請","application_period":"随時公募（カタログ登録製品が対象）","key_points":["カタログから選ぶだけの簡単な申請","IoT・ロボット等の汎用製品が対象","賃上げ要件達成で補助上限1.5倍","一般型（最大1億円）とは別制度"],"comparison_with_general":{"カタログ注文型":"最大1,500万円、カタログ掲載製品、簡易申請","一般型":"最大1億円、オーダーメイド設備、詳細計画必要"},"contact":"中小企業省力化投資補助金事務局","official_url":"https://shoryokuka.smrj.go.jp/catalog/","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SHORYOKUKA-CATALOG';

