-- Phase 10 Part 2: 新規50件（#287〜#336）
-- 農林水産業、医薬品・バイオ、宇宙・航空、通信・情報、防衛・安全保障、教育ICT

-- #287 農業次世代人材投資資金（経営開始型）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('NOGYO-JISEDAI-KEIEI', '農業次世代人材投資資金（経営開始型）', 'MAFF', '農林水産省', '00', '["subsidy","agriculture"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('NOGYO-JISEDAI-KEIEI', 'manual', '農業次世代人材投資資金（経営開始型）', 1500000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"新規就農者の経営開始直後の生活を支援","target":"独立・自営就農する50歳未満の者","amount":"年間150万円（最長3年間）","period":"令和8年度","url":"https://www.maff.go.jp/j/new_farmer/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'NOGYO-JISEDAI-KEIEI', 1);

-- #288 みどりの食料システム戦略推進交付金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('MIDORI-SHOKURYOU', 'みどりの食料システム戦略推進交付金', 'MAFF', '農林水産省', '00', '["subsidy","agriculture","environment"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('MIDORI-SHOKURYOU', 'manual', 'みどりの食料システム戦略推進交付金', 30000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"化学農薬・化学肥料の低減、有機農業の拡大等を推進","target":"農業者、農業法人、地方公共団体","amount":"取組内容により数百万〜数千万円","period":"令和8年度","url":"https://www.maff.go.jp/j/kanbo/kankyo/seisaku/midori/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'MIDORI-SHOKURYOU', 1);

-- #289 畜産クラスター事業（再掲回避・別枠）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('CHIKUSAN-SEISAN', '畜産・酪農収益力強化整備等特別対策事業', 'MAFF', '農林水産省', '00', '["subsidy","agriculture"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('CHIKUSAN-SEISAN', 'manual', '畜産・酪農収益力強化整備等特別対策事業', 500000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"畜産・酪農の生産基盤強化のための施設整備等を支援","target":"畜産農家、農業法人、畜産クラスター協議会","amount":"施設整備費の1/2以内","period":"令和8年度","url":"https://www.maff.go.jp/j/chikusan/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'CHIKUSAN-SEISAN', 1);

-- #290 農地中間管理事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('NOUCHI-CHUUKAN', '農地中間管理事業', 'MAFF', '農林水産省', '00', '["subsidy","agriculture"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('NOUCHI-CHUUKAN', 'manual', '農地中間管理事業（農地バンク）', NULL, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"農地の集積・集約化を促進するための農地中間管理機構の活動を支援","target":"農地を借りたい農業者・農業法人","amount":"地域集積協力金：10aあたり2〜3.6万円","period":"通年","url":"https://www.maff.go.jp/j/keiei/koukai/nouchi_seido/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'NOUCHI-CHUUKAN', 1);

-- #291 鳥獣被害防止総合対策交付金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('CHOUJU-HIGAI', '鳥獣被害防止総合対策交付金', 'MAFF', '農林水産省', '00', '["subsidy","agriculture"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('CHOUJU-HIGAI', 'manual', '鳥獣被害防止総合対策交付金', 20000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"イノシシ・シカ等の鳥獣被害防止のための侵入防止柵設置・捕獲活動等を支援","target":"市町村、鳥獣被害対策実施隊、農業者","amount":"侵入防止柵等の資材費・捕獲活動経費","period":"令和8年度","url":"https://www.maff.go.jp/j/seisan/tyozyu/higai/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'CHOUJU-HIGAI', 1);

-- #292 水産加工資金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('SUISAN-KAKOU', '水産加工資金', 'MAFF', '農林水産省', '00', '["finance","fishery"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('SUISAN-KAKOU', 'manual', '水産加工資金', 100000000, '低利融資', '全国', '2026-04-01', '2027-03-31', '{"overview":"水産加工業者の施設整備・運転資金を低利融資で支援","target":"水産加工業者","amount":"融資限度額1億円（運転資金5,000万円）","period":"通年","url":"https://www.jfa.maff.go.jp/","source":"農林水産省（水産庁）"}', datetime('now'), datetime('now', '+90 days'), 90, 'SUISAN-KAKOU', 1);

-- #293 AMED創薬支援推進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('AMED-SOUYAKU', 'AMED創薬支援推進事業', 'AMED', 'AMED', '00', '["research","health"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('AMED-SOUYAKU', 'manual', 'AMED創薬支援推進事業', 100000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"創薬シーズの実用化を加速するための研究開発を支援","target":"大学・研究機関・製薬企業","amount":"1課題あたり数千万〜1億円","period":"令和8年度","url":"https://www.amed.go.jp/","source":"AMED"}', datetime('now'), datetime('now', '+90 days'), 90, 'AMED-SOUYAKU', 1);

-- #294 再生医療実用化研究事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('SAISEI-IRYOU', '再生医療実用化研究事業', 'AMED', 'AMED', '00', '["research","health"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('SAISEI-IRYOU', 'manual', '再生医療実用化研究事業', 200000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"iPS細胞等を活用した再生医療の実用化研究を支援","target":"大学・研究機関・企業","amount":"1課題あたり数千万〜2億円","period":"令和8年度","url":"https://www.amed.go.jp/program/list/17/01/001.html","source":"AMED"}', datetime('now'), datetime('now', '+90 days'), 90, 'SAISEI-IRYOU', 1);

-- #295 医療機器開発支援事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('IRYOU-KIKI-KAIHATSU', '医療機器開発支援事業', 'AMED', 'AMED', '00', '["research","health","manufacturing"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('IRYOU-KIKI-KAIHATSU', 'manual', '医療機器開発支援事業', 100000000, '2/3', '全国', '2026-04-01', '2027-03-31', '{"overview":"革新的な医療機器の開発・薬事承認取得を支援","target":"医療機器メーカー、大学、研究機関","amount":"上限1億円（補助率2/3）","period":"令和8年度","url":"https://www.amed.go.jp/","source":"AMED"}', datetime('now'), datetime('now', '+90 days'), 90, 'IRYOU-KIKI-KAIHATSU', 1);

-- #296 JAXA宇宙探査イノベーションハブ
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('JAXA-TANSAKAI', 'JAXA宇宙探査イノベーションハブ', 'JAXA', 'JAXA', '00', '["research","technology"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('JAXA-TANSAKAI', 'manual', 'JAXA宇宙探査イノベーションハブ共同研究', 50000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"宇宙探査に必要な技術の地上応用を含む共同研究を支援","target":"企業、大学、研究機関","amount":"1テーマ数百万〜5,000万円","period":"令和8年度","url":"https://www.ihub-tansa.jaxa.jp/","source":"JAXA"}', datetime('now'), datetime('now', '+90 days'), 90, 'JAXA-TANSAKAI', 1);

-- #297 衛星データ利活用促進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('EISEI-DATA', '衛星データ利活用促進事業', 'METI', '経済産業省', '00', '["subsidy","technology"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('EISEI-DATA', 'manual', '衛星データ利活用促進事業（Tellus等）', 30000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"衛星データの利活用による新ビジネス創出を支援","target":"企業、スタートアップ、研究機関","amount":"1課題数百万〜3,000万円","period":"令和8年度","url":"https://www.tellusxdp.com/","source":"経済産業省"}', datetime('now'), datetime('now', '+90 days'), 90, 'EISEI-DATA', 1);

-- #298 GIGAスクール構想（学校ICT環境整備）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('GIGA-SCHOOL', 'GIGAスクール構想推進事業', 'MEXT', '文部科学省', '00', '["subsidy","education","digital"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('GIGA-SCHOOL', 'manual', 'GIGAスクール構想推進事業（第2期端末更新）', 55000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"児童生徒1人1台端末の更新・高速ネットワーク整備を支援","target":"地方公共団体（教育委員会）","amount":"1台あたり5.5万円（端末更新）","period":"令和8年度","url":"https://www.mext.go.jp/a_menu/other/index_00001.htm","source":"文部科学省"}', datetime('now'), datetime('now', '+90 days'), 90, 'GIGA-SCHOOL', 1);

-- #299 学校施設環境改善交付金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('GAKKOU-KAIZEN', '学校施設環境改善交付金', 'MEXT', '文部科学省', '00', '["subsidy","education","facility"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('GAKKOU-KAIZEN', 'manual', '学校施設環境改善交付金（空調・トイレ・バリアフリー）', 500000000, '1/3', '全国', '2026-04-01', '2027-03-31', '{"overview":"学校施設の空調設備、トイレ改修、バリアフリー化等を支援","target":"地方公共団体","amount":"工事費の1/3（地方財政措置あり）","period":"令和8年度","url":"https://www.mext.go.jp/a_menu/shotou/zyosei/","source":"文部科学省"}', datetime('now'), datetime('now', '+90 days'), 90, 'GAKKOU-KAIZEN', 1);

-- #300 私立学校施設整備費補助金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('SHIRITSU-SEIBI', '私立学校施設整備費補助金', 'MEXT', '文部科学省', '00', '["subsidy","education","facility"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('SHIRITSU-SEIBI', 'manual', '私立学校施設整備費補助金（耐震・省エネ）', 200000000, '1/3', '全国', '2026-04-01', '2027-03-31', '{"overview":"私立学校の耐震化・省エネ化・バリアフリー化等の施設整備を支援","target":"学校法人","amount":"工事費の1/3以内","period":"令和8年度","url":"https://www.mext.go.jp/a_menu/koutou/shinkou/","source":"文部科学省"}', datetime('now'), datetime('now', '+90 days'), 90, 'SHIRITSU-SEIBI', 1);

-- #301 Beyond 5G研究開発促進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('BEYOND-5G', 'Beyond 5G研究開発促進事業', 'MIC', '総務省', '00', '["research","technology"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('BEYOND-5G', 'manual', 'Beyond 5G研究開発促進事業（6G基盤技術）', 500000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"2030年代の6G実現に向けた要素技術・基盤技術の研究開発を推進","target":"企業、大学、研究機関","amount":"1課題数千万〜5億円","period":"令和8年度","url":"https://www.soumu.go.jp/menu_seisaku/ictseisaku/ict_kiban/beyond5G/","source":"総務省（NICT）"}', datetime('now'), datetime('now', '+90 days'), 90, 'BEYOND-5G', 1);

-- #302 地域IoT実装推進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('CHIIKI-IOT', '地域IoT実装推進事業', 'MIC', '総務省', '00', '["subsidy","digital","regional"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('CHIIKI-IOT', 'manual', '地域IoT実装推進事業', 20000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"地域課題解決のためのIoT・AI等の実装を支援","target":"地方公共団体、地域団体、民間企業","amount":"上限2,000万円（補助率1/2）","period":"令和8年度","url":"https://www.soumu.go.jp/menu_seisaku/ictseisaku/","source":"総務省"}', datetime('now'), datetime('now', '+90 days'), 90, 'CHIIKI-IOT', 1);

-- #303 ローカル5G導入促進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('LOCAL-5G', 'ローカル5G導入促進事業', 'MIC', '総務省', '00', '["subsidy","digital","technology"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('LOCAL-5G', 'manual', 'ローカル5G導入促進事業（工場・農業・医療等）', 50000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"工場、農業、医療等の現場でのローカル5G導入実証を支援","target":"企業、地方公共団体、医療機関等","amount":"上限5,000万円（補助率1/2）","period":"令和8年度","url":"https://www.soumu.go.jp/main_sosiki/joho_tsusin/top/local_support/","source":"総務省"}', datetime('now'), datetime('now', '+90 days'), 90, 'LOCAL-5G', 1);

-- #304 情報通信技術利活用事業費補助金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('ICT-RIKATSUYOU', '情報通信技術利活用事業費補助金', 'MIC', '総務省', '00', '["subsidy","digital"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('ICT-RIKATSUYOU', 'manual', '情報通信技術利活用事業費補助金', 30000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"ICT利活用による地域課題解決モデルの構築を支援","target":"地方公共団体、民間企業","amount":"上限3,000万円（補助率1/2）","period":"令和8年度","url":"https://www.soumu.go.jp/","source":"総務省"}', datetime('now'), datetime('now', '+90 days'), 90, 'ICT-RIKATSUYOU', 1);

-- #305 防衛装備品サプライチェーン強靱化事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('BOUEI-SUPPLY', '防衛装備品サプライチェーン強靱化事業', 'MOD', '防衛省', '00', '["subsidy","manufacturing","security"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('BOUEI-SUPPLY', 'manual', '防衛装備品サプライチェーン強靱化事業', 100000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"防衛装備品のサプライチェーン強靱化のための設備投資等を支援","target":"防衛装備品の製造・修理に関わる中小企業","amount":"上限1億円（補助率1/2）","period":"令和8年度","url":"https://www.mod.go.jp/atla/","source":"防衛省（防衛装備庁）"}', datetime('now'), datetime('now', '+90 days'), 90, 'BOUEI-SUPPLY', 1);

-- #306 経済安全保障重要技術育成プログラム（K Program）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('K-PROGRAM', '経済安全保障重要技術育成プログラム', 'CAO', '内閣府', '00', '["research","technology","security"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('K-PROGRAM', 'manual', '経済安全保障重要技術育成プログラム（K Program）', 5000000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"AI・量子・宇宙・海洋等の経済安全保障上重要な先端技術の育成","target":"大学、研究機関、企業","amount":"1課題数億〜数十億円","period":"令和8年度","url":"https://www8.cao.go.jp/cstp/anzen_anshin/kprogram.html","source":"内閣府"}', datetime('now'), datetime('now', '+90 days'), 90, 'K-PROGRAM', 1);

-- #307 福祉車両購入費補助金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('FUKUSHI-SHARYO', '福祉車両購入費補助金', 'MHLW', '厚生労働省', '00', '["subsidy","health","mobility"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('FUKUSHI-SHARYO', 'manual', '福祉車両購入費補助金（介護送迎用等）', 2000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"社会福祉法人等が使用する送迎用福祉車両の購入を支援","target":"社会福祉法人、NPO、介護事業者","amount":"上限200万円（補助率1/2）","period":"令和8年度","url":"https://www.wam.go.jp/","source":"厚生労働省（福祉医療機構）"}', datetime('now'), datetime('now', '+90 days'), 90, 'FUKUSHI-SHARYO', 1);

-- #308 介護施設等整備事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('KAIGO-SHISETSU', '介護施設等整備事業', 'MHLW', '厚生労働省', '00', '["subsidy","health","facility"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('KAIGO-SHISETSU', 'manual', '地域介護・福祉空間整備等施設整備交付金', 300000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"介護施設（特養・グループホーム等）の整備費を支援","target":"社会福祉法人、医療法人等","amount":"施設種類により異なる（特養1床あたり450万円等）","period":"令和8年度","url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/","source":"厚生労働省"}', datetime('now'), datetime('now', '+90 days'), 90, 'KAIGO-SHISETSU', 1);

-- #309 認知症施策推進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('NINCHISHOU-SUISHIN', '認知症施策推進事業', 'MHLW', '厚生労働省', '00', '["subsidy","health"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('NINCHISHOU-SUISHIN', 'manual', '認知症施策推進事業（認知症サポーター等）', 10000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"認知症の人にやさしい地域づくりのための啓発・支援事業","target":"市区町村、地域包括支援センター","amount":"事業規模により異なる","period":"令和8年度","url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000076236.html","source":"厚生労働省"}', datetime('now'), datetime('now', '+90 days'), 90, 'NINCHISHOU-SUISHIN', 1);

-- #310 障害者グループホーム整備事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('SHOUGAI-GH', '障害者グループホーム等整備事業', 'MHLW', '厚生労働省', '00', '["subsidy","health","facility"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('SHOUGAI-GH', 'manual', '障害者グループホーム等整備事業', 50000000, '3/4', '全国', '2026-04-01', '2027-03-31', '{"overview":"障害者グループホームの新設・改修を支援","target":"社会福祉法人、NPO法人等","amount":"施設整備費の3/4以内","period":"令和8年度","url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/shougaishahukushi/","source":"厚生労働省"}', datetime('now'), datetime('now', '+90 days'), 90, 'SHOUGAI-GH', 1);

-- #311 地域生活支援事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('CHIIKI-SEIKATSU-SHIEN', '地域生活支援事業', 'MHLW', '厚生労働省', '00', '["subsidy","health"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('CHIIKI-SEIKATSU-SHIEN', 'manual', '地域生活支援事業（障害者の社会参加支援）', NULL, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"障害者の日常生活・社会生活を支援する各種事業","target":"市区町村、都道府県","amount":"国1/2以内の補助","period":"令和8年度","url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/shougaishahukushi/chiiki/","source":"厚生労働省"}', datetime('now'), datetime('now', '+90 days'), 90, 'CHIIKI-SEIKATSU-SHIEN', 1);

-- #312 スポーツ施設整備補助金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('SPORTS-SHISETSU', 'スポーツ施設整備補助金', 'MEXT', '文部科学省', '00', '["subsidy","sports","facility"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('SPORTS-SHISETSU', 'manual', 'スポーツ施設整備費補助金', 300000000, '1/3', '全国', '2026-04-01', '2027-03-31', '{"overview":"地方公共団体のスポーツ施設の新設・改修を支援","target":"地方公共団体","amount":"工事費の1/3以内","period":"令和8年度","url":"https://www.mext.go.jp/sports/","source":"文部科学省（スポーツ庁）"}', datetime('now'), datetime('now', '+90 days'), 90, 'SPORTS-SHISETSU', 1);

-- #313 地域スポーツコミッション支援事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('SPORTS-COMMISSION', '地域スポーツコミッション支援事業', 'MEXT', '文部科学省', '00', '["subsidy","sports","regional"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('SPORTS-COMMISSION', 'manual', '地域スポーツコミッション支援事業', 10000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"スポーツツーリズム・合宿誘致等の地域スポーツ振興を支援","target":"地域スポーツコミッション、地方公共団体","amount":"上限1,000万円","period":"令和8年度","url":"https://www.mext.go.jp/sports/b_menu/sports/mcatetop08/","source":"文部科学省（スポーツ庁）"}', datetime('now'), datetime('now', '+90 days'), 90, 'SPORTS-COMMISSION', 1);

-- #314 過疎地域持続的発展支援交付金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('KASO-JIZOKU', '過疎地域持続的発展支援交付金', 'MIC', '総務省', '00', '["subsidy","regional"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('KASO-JIZOKU', 'manual', '過疎地域持続的発展支援交付金', 30000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"過疎地域の移住・定住促進、産業振興、生活支援等を支援","target":"過疎地域の市町村","amount":"1市町村上限3,000万円","period":"令和8年度","url":"https://www.soumu.go.jp/main_sosiki/jichi_gyousei/c-gyousei/2001/kaso/kasomain.htm","source":"総務省"}', datetime('now'), datetime('now', '+90 days'), 90, 'KASO-JIZOKU', 1);

-- #315 離島活性化交付金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('RITOU-KASSEI', '離島活性化交付金', 'MLIT', '国土交通省', '00', '["subsidy","regional"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('RITOU-KASSEI', 'manual', '離島活性化交付金', 30000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"離島地域の定住促進、産業振興、交通確保等を支援","target":"離島の市町村","amount":"上限3,000万円（補助率1/2）","period":"令和8年度","url":"https://www.mlit.go.jp/kokudoseisaku/chirit/kokudoseisaku_chirit_tk_000067.html","source":"国土交通省"}', datetime('now'), datetime('now', '+90 days'), 90, 'RITOU-KASSEI', 1);

-- #316 食品産業の輸出向けHACCP等対応施設整備事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('HACCP-YUSHUTSU', '食品産業輸出向けHACCP等対応施設整備事業', 'MAFF', '農林水産省', '00', '["subsidy","food","export"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('HACCP-YUSHUTSU', 'manual', '食品産業輸出向けHACCP等対応施設整備事業', 500000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"食品輸出に必要なHACCP認証取得のための施設整備を支援","target":"食品製造業者","amount":"上限5億円（補助率1/2）","period":"令和8年度","url":"https://www.maff.go.jp/j/shokusan/export/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'HACCP-YUSHUTSU', 1);

-- #317 農林水産物・食品輸出促進緊急対策事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('NOUSUI-YUSHUTSU', '農林水産物・食品輸出促進事業', 'MAFF', '農林水産省', '00', '["subsidy","agriculture","export"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('NOUSUI-YUSHUTSU', 'manual', '農林水産物・食品輸出促進事業（輸出額5兆円目標）', 50000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"農林水産物・食品の輸出拡大のためのマーケティング・販路開拓を支援","target":"農林水産事業者、食品メーカー、輸出団体","amount":"上限5,000万円（補助率1/2）","period":"令和8年度","url":"https://www.maff.go.jp/j/shokusan/export/","source":"農林水産省"}', datetime('now'), datetime('now', '+90 days'), 90, 'NOUSUI-YUSHUTSU', 1);

-- #318 国土強靱化関係交付金（自治体向け）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('KOKUDO-KOUFUKIN', '国土強靱化関係交付金', 'CAO', '内閣府', '00', '["subsidy","infrastructure","disaster"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('KOKUDO-KOUFUKIN', 'manual', '国土強靱化関係予算・交付金', NULL, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"防災・減災、国土強靱化のための5か年加速化対策を推進","target":"地方公共団体、インフラ管理者","amount":"事業規模により異なる","period":"5か年加速化対策（〜令和7年度、延長検討中）","url":"https://www.cas.go.jp/jp/seisaku/kokudo_kyoujinka/","source":"内閣府（国土強靱化推進室）"}', datetime('now'), datetime('now', '+90 days'), 90, 'KOKUDO-KOUFUKIN', 1);

-- #319 上下水道耐震化等推進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('JOUSUIDOU-TAISHIN', '上下水道耐震化等推進事業', 'MLIT', '国土交通省', '00', '["subsidy","infrastructure"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('JOUSUIDOU-TAISHIN', 'manual', '上下水道耐震化等推進事業', 500000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"上下水道施設の耐震化・老朽化対策を支援","target":"地方公共団体（水道事業者）","amount":"工事費の1/2以内","period":"令和8年度","url":"https://www.mlit.go.jp/mizukokudo/sewerage/","source":"国土交通省"}', datetime('now'), datetime('now', '+90 days'), 90, 'JOUSUIDOU-TAISHIN', 1);

-- #320 道路メンテナンス事業補助金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('DOURO-MAINTENANCE', '道路メンテナンス事業補助金', 'MLIT', '国土交通省', '00', '["subsidy","infrastructure"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('DOURO-MAINTENANCE', 'manual', '道路メンテナンス事業補助金（橋梁・トンネル等）', NULL, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"橋梁・トンネル等の道路施設の点検・修繕を支援","target":"地方公共団体","amount":"修繕費の1/2以内","period":"令和8年度","url":"https://www.mlit.go.jp/road/sisaku/yobohozen/","source":"国土交通省"}', datetime('now'), datetime('now', '+90 days'), 90, 'DOURO-MAINTENANCE', 1);

-- #321 クラウドファンディング活用型まちづくりファンド
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('CF-MACHIDUKURI', 'クラウドファンディング活用型まちづくりファンド', 'MLIT', '国土交通省', '00', '["subsidy","regional","finance"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('CF-MACHIDUKURI', 'manual', 'クラウドファンディング活用型まちづくりファンド支援事業', 5000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"CFで集めた資金と同額をマッチング補助するまちづくり支援","target":"まちづくり会社、NPO、地方公共団体","amount":"CF調達額と同額（上限500万円）","period":"令和8年度","url":"https://www.minto.or.jp/products/fund.html","source":"国土交通省（民間都市開発推進機構）"}', datetime('now'), datetime('now', '+90 days'), 90, 'CF-MACHIDUKURI', 1);

-- #322 空き家対策総合支援事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('AKIYA-SOUGOU', '空き家対策総合支援事業', 'MLIT', '国土交通省', '00', '["subsidy","housing","regional"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('AKIYA-SOUGOU', 'manual', '空き家対策総合支援事業', 50000000, '1/2', '全国', '2026-04-01', '2027-03-31', '{"overview":"空き家の除却・利活用・管理不全対策を総合的に支援","target":"市区町村","amount":"除却・利活用費の1/2以内","period":"令和8年度","url":"https://www.mlit.go.jp/jutakukentiku/house/jutakukentiku_house_tk3_000035.html","source":"国土交通省"}', datetime('now'), datetime('now', '+90 days'), 90, 'AKIYA-SOUGOU', 1);

-- #323 グリーン住宅ポイント（住宅エコポイント後継）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('JUTAKU-ECO-POINT', '住宅省エネキャンペーン（子育てエコホーム支援事業後継）', 'MLIT', '国土交通省', '00', '["subsidy","housing","environment"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('JUTAKU-ECO-POINT', 'manual', '住宅省エネキャンペーン2026', 1000000, '定額', '全国', '2026-04-01', '2027-03-31', '{"overview":"省エネ性能の高い住宅の新築・リフォームを支援","target":"住宅取得者、リフォーム実施者","amount":"新築：最大100万円、リフォーム：最大60万円","period":"令和8年度","url":"https://www.mlit.go.jp/jutakukentiku/house/","source":"国土交通省"}', datetime('now'), datetime('now', '+90 days'), 90, 'JUTAKU-ECO-POINT', 1);

-- #324 長期優良住宅化リフォーム推進事業
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('CHOUKI-REFORM', '長期優良住宅化リフォーム推進事業', 'MLIT', '国土交通省', '00', '["subsidy","housing"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('CHOUKI-REFORM', 'manual', '長期優良住宅化リフォーム推進事業', 2500000, '1/3', '全国', '2026-04-01', '2027-02-28', '{"overview":"既存住宅の長寿命化・省エネ化リフォームを支援","target":"住宅所有者、リフォーム事業者","amount":"1戸あたり上限100〜250万円（補助率1/3）","period":"令和8年度","url":"https://www.kenken.go.jp/chouki_r/","source":"国土交通省"}', datetime('now'), datetime('now', '+90 days'), 90, 'CHOUKI-REFORM', 1);

-- #325 沖縄振興特別推進交付金（一括交付金）
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('OKINAWA-IKKATSU', '沖縄振興特別推進交付金（一括交付金）', 'CAO', '内閣府', '47', '["subsidy","regional"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('OKINAWA-IKKATSU', 'manual', '沖縄振興特別推進交付金（ソフト交付金）', NULL, '8/10', '沖縄県', '2026-04-01', '2027-03-31', '{"overview":"沖縄県の自主的な施策を支援するための一括交付金","target":"沖縄県、県内市町村","amount":"補助率8/10（ソフト事業）","period":"令和8年度","url":"https://www8.cao.go.jp/okinawa/","source":"内閣府沖縄担当"}', datetime('now'), datetime('now', '+90 days'), 90, 'OKINAWA-IKKATSU', 1);

-- #326 アイヌ政策推進交付金
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('AINU-SUISHIN', 'アイヌ政策推進交付金', 'CAO', '内閣府', '01', '["subsidy","regional","culture"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('AINU-SUISHIN', 'manual', 'アイヌ政策推進交付金', 30000000, '8/10', '北海道', '2026-04-01', '2027-03-31', '{"overview":"アイヌ文化の振興・伝承、生活向上等の施策を推進","target":"北海道内の市町村","amount":"事業費の8/10以内","period":"令和8年度","url":"https://www.kantei.go.jp/jp/singi/ainusuishin/","source":"内閣府（アイヌ総合政策室）"}', datetime('now'), datetime('now', '+90 days'), 90, 'AINU-SUISHIN', 1);

-- #327〜#336: 地方自治体独自（都道府県レベル）10件
INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('MIYAGI-DX', '宮城県中小企業DX推進補助金', 'MIYAGI', '宮城県', '04', '["subsidy","digital"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('MIYAGI-DX', 'manual', '宮城県中小企業DX推進補助金', 2000000, '2/3', '宮城県', '2026-04-01', '2027-02-28', '{"overview":"宮城県内中小企業のDX推進を支援","target":"宮城県内の中小企業","amount":"上限200万円（補助率2/3）","period":"令和8年度","url":"https://www.pref.miyagi.jp/","source":"宮城県"}', datetime('now'), datetime('now', '+90 days'), 90, 'MIYAGI-DX', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('IBARAKI-INNOV', '茨城県イノベーション推進補助金', 'IBARAKI', '茨城県', '08', '["subsidy","technology"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('IBARAKI-INNOV', 'manual', '茨城県イノベーション推進補助金', 5000000, '1/2', '茨城県', '2026-04-01', '2027-02-28', '{"overview":"茨城県内の中小企業のイノベーション活動を支援","target":"茨城県内に事業所を有する中小企業","amount":"上限500万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.ibaraki.jp/","source":"茨城県"}', datetime('now'), datetime('now', '+90 days'), 90, 'IBARAKI-INNOV', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('GUNMA-SOUGYOU', '群馬県創業支援補助金', 'GUNMA', '群馬県', '10', '["subsidy","startup"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('GUNMA-SOUGYOU', 'manual', '群馬県創業支援補助金', 1000000, '2/3', '群馬県', '2026-04-01', '2027-02-28', '{"overview":"群馬県内で創業する方の初期費用を支援","target":"群馬県内で創業予定者","amount":"上限100万円（補助率2/3）","period":"令和8年度","url":"https://www.pref.gunma.jp/","source":"群馬県"}', datetime('now'), datetime('now', '+90 days'), 90, 'GUNMA-SOUGYOU', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('TOYAMA-MONO', '富山県ものづくり産業振興補助金', 'TOYAMA', '富山県', '16', '["subsidy","manufacturing"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('TOYAMA-MONO', 'manual', '富山県ものづくり産業振興補助金', 5000000, '1/2', '富山県', '2026-04-01', '2027-02-28', '{"overview":"富山県内の製造業の新製品開発等を支援","target":"富山県内の中小製造業者","amount":"上限500万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.toyama.jp/","source":"富山県"}', datetime('now'), datetime('now', '+90 days'), 90, 'TOYAMA-MONO', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('MIE-KANKOU', '三重県観光産業振興補助金', 'MIE', '三重県', '24', '["subsidy","tourism"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('MIE-KANKOU', 'manual', '三重県観光産業振興補助金', 3000000, '1/2', '三重県', '2026-04-01', '2027-02-28', '{"overview":"三重県内の観光事業者の事業拡大を支援","target":"三重県内の観光関連事業者","amount":"上限300万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.mie.lg.jp/","source":"三重県"}', datetime('now'), datetime('now', '+90 days'), 90, 'MIE-KANKOU', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('NARA-BUNKA', '奈良県文化財活用補助金', 'NARA', '奈良県', '29', '["subsidy","culture"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('NARA-BUNKA', 'manual', '奈良県文化財活用補助金', 5000000, '2/3', '奈良県', '2026-04-01', '2027-02-28', '{"overview":"奈良県内の文化財の保存・活用事業を支援","target":"文化財所有者、寺社、NPO等","amount":"上限500万円（補助率2/3）","period":"令和8年度","url":"https://www.pref.nara.jp/","source":"奈良県"}', datetime('now'), datetime('now', '+90 days'), 90, 'NARA-BUNKA', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('KAGAWA-FOOD', '香川県食品産業振興補助金', 'KAGAWA', '香川県', '37', '["subsidy","food"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('KAGAWA-FOOD', 'manual', '香川県食品産業振興補助金', 3000000, '1/2', '香川県', '2026-04-01', '2027-02-28', '{"overview":"香川県内の食品事業者の新商品開発等を支援","target":"香川県内の食品製造・加工業者","amount":"上限300万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.kagawa.lg.jp/","source":"香川県"}', datetime('now'), datetime('now', '+90 days'), 90, 'KAGAWA-FOOD', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('NAGASAKI-ZOSEN', '長崎県造船関連産業振興補助金', 'NAGASAKI', '長崎県', '42', '["subsidy","manufacturing"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('NAGASAKI-ZOSEN', 'manual', '長崎県造船関連産業振興補助金', 10000000, '1/2', '長崎県', '2026-04-01', '2027-02-28', '{"overview":"長崎県内の造船関連産業の技術開発・人材育成を支援","target":"長崎県内の造船関連企業","amount":"上限1,000万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.nagasaki.jp/","source":"長崎県"}', datetime('now'), datetime('now', '+90 days'), 90, 'NAGASAKI-ZOSEN', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('OITA-ONSEN', '大分県温泉資源活用補助金', 'OITA', '大分県', '44', '["subsidy","tourism","energy"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('OITA-ONSEN', 'manual', '大分県温泉資源活用事業補助金', 5000000, '1/2', '大分県', '2026-04-01', '2027-02-28', '{"overview":"大分県内の温泉資源を活用した観光・エネルギー事業を支援","target":"温泉事業者、観光事業者","amount":"上限500万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.oita.jp/","source":"大分県"}', datetime('now'), datetime('now', '+90 days'), 90, 'OITA-ONSEN', 1);

INSERT OR IGNORE INTO subsidy_canonical (id, name, issuer_code, issuer_name, prefecture_code, category_codes, first_seen_at, last_updated_at, is_active, created_at, updated_at) VALUES ('KAGOSHIMA-NOUGYOU', '鹿児島県スマート農業推進補助金', 'KAGOSHIMA', '鹿児島県', '46', '["subsidy","agriculture","digital"]', datetime('now'), datetime('now'), 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO subsidy_cache (id, source, title, subsidy_max_limit, subsidy_rate, target_area_search, acceptance_start_datetime, acceptance_end_datetime, detail_json, cached_at, expires_at, detail_score, canonical_id, is_visible) VALUES ('KAGOSHIMA-NOUGYOU', 'manual', '鹿児島県スマート農業推進補助金', 3000000, '1/2', '鹿児島県', '2026-04-01', '2027-02-28', '{"overview":"鹿児島県内の農業者のスマート農業機器導入を支援","target":"鹿児島県内の農業者・農業法人","amount":"上限300万円（補助率1/2）","period":"令和8年度","url":"https://www.pref.kagoshima.jp/","source":"鹿児島県"}', datetime('now'), datetime('now', '+90 days'), 90, 'KAGOSHIMA-NOUGYOU', 1);
