-- Phase 7: 公募要領PDFベースの detail_json 一括更新
-- 対象: GYOMU-KAIZEN-R7 (75→95), SHINJIGYO-03, SEICHOU-KASOKU-02, MONODUKURI-23, MONODUKURI-GLOBAL, JIGYOSHOKEI-MA-14 (90→95)
-- + IT補助金→デジタル化・AI導入補助金2026 名称変更反映
-- 情報源: 公式PDF公募要領（厚労省、SMRJ、中小企業庁）
-- 更新日: 2026-02-08

-- 1. GYOMU-KAIZEN-R7: 業務改善助成金（令和7年度）75→95
UPDATE subsidy_cache SET detail_json = json('{"title":"業務改善助成金（令和7年度）","version":"令和7年度","subsidy_overview":{"summary":"事業場内最低賃金を30円以上引き上げ、生産性向上に資する設備投資等を行った中小企業・小規模事業者に対し、設備投資費用の一部を助成する制度","purpose":"最低賃金引上げと生産性向上の同時実現","budget":"352億円（令和7年度補正予算）"},"subsidy_amount":{"max":"600万円","min":"30万円","tiers":[{"raise_amount":"30円以上","1人":"30万円","2-3人":"50万円","4-6人":"70万円","7人以上":"100万円","10人以上（特例）":"120万円"},{"raise_amount":"45円以上","1人":"45万円","2-3人":"90万円","4-6人":"150万円","7人以上":"270万円","10人以上（特例）":"300万円"},{"raise_amount":"60円以上","1人":"60万円","2-3人":"120万円","4-6人":"200万円","7人以上":"360万円","10人以上（特例）":"400万円"},{"raise_amount":"90円以上","1人":"90万円","2-3人":"180万円","4-6人":"300万円","7人以上":"540万円","10人以上（特例）":"600万円"}],"note":"10人以上の区分は特例事業者のみ適用"},"subsidy_rate":{"under_1000":"4/5","over_1000":"3/4","note":"事業場内最低賃金額により異なる"},"target_requirements":{"business_type":"中小企業・小規模事業者（みなし大企業は対象外）","wage_condition":"事業場内最低賃金と地域別最低賃金の差額が50円以内","employment_period":"雇用期間6か月以上の労働者が対象","disqualification":"解雇や賃金引下げ等の不交付事由がないこと"},"eligible_expenses":{"general":["生産性向上に資する設備投資（POSレジ、特殊車両、顧客管理システム等）","経営コンサルティング","人材育成・教育訓練"],"special_exception":["PC・スマホ・タブレット","定員7人以上または200万円以下の乗用・貨物自動車"],"special_condition":"特例事業者（利益率が前年同月比3%ポイント以上低下）のみ"},"application_period":{"period_1":"令和7年4月14日～6月13日","period_2":"令和7年6月14日～地域別最低賃金改定日の前日","note":"予算がなくなり次第終了"},"application_method":"管轄の都道府県労働局 雇用環境・均等部（室）に交付申請書と事業実施計画書を提出","business_completion":"原則 令和8年1月31日まで（やむを得ない場合は理由書提出により令和8年3月31日まで延長可）","review_points":["交付決定前に導入した設備は助成対象外","同一事業場の申請は年度内1回まで","地域別最低賃金発効日までに賃金引上げを完了し就業規則等に反映"],"contact":{"call_center":"0120-366-440","hours":"平日9:00～17:00","submission":"各都道府県労働局 雇用環境・均等部（室）"},"official_url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/shienjigyou/03.html","pdf_source":"https://www.mhlw.go.jp/content/11200000/001471309.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'GYOMU-KAIZEN-R7';

-- 2. SHINJIGYO-03: 中小企業新事業進出促進補助金（第3回公募）90→95
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業新事業進出促進補助金（第3回公募）","version":"第3回公募（令和7年12月23日公開）","subsidy_overview":{"summary":"中小企業が新市場や高付加価値事業へ進出することを支援し、生産性向上と賃上げを促進する補助金","purpose":"新事業進出による成長と賃上げの実現"},"subsidy_amount":{"by_employees":[{"employees":"20人以下","normal":"2,500万円","with_wage_up":"3,000万円"},{"employees":"21～50人","normal":"4,000万円","with_wage_up":"5,000万円"},{"employees":"51～100人","normal":"5,500万円","with_wage_up":"7,000万円"},{"employees":"101人以上","normal":"7,000万円","with_wage_up":"9,000万円"}],"min":"750万円（補助下限）","wage_up_condition":"事業場内最低賃金+50円 かつ 給与支給総額+6%を達成"},"subsidy_rate":"1/2","target_requirements":{"business_type":"日本国内に本社及び補助事業実施場所を有する中小企業者","exclusions":["課税所得の年平均額が15億円超","従業員数0名","創業1年未満"],"application_method":"GビズIDプライムアカウントによる電子申請のみ（代理申請不可）"},"eligible_expenses":["機械装置・システム構築費（必須）","建物費（必須：いずれか1つ以上）","運搬費","技術導入費","知的財産権等関連経費","外注費","専門家経費","クラウドサービス利用費","広告宣伝・販売促進費"],"application_period":{"start":"令和7年12月23日（火）","acceptance_start":"令和8年2月17日（火）","deadline":"令和8年3月26日（木）18:00厳守"},"review_points":["補助対象事業としての適格性","新規事業の新市場性・高付加価値性","新規事業の有望度（競合分析含む）","事業の実現可能性（財務状況・体制）","公的補助の必要性","政策面（地域経済波及等）","口頭審査（Zoom等でオンライン実施）"],"business_period":"交付決定日から14か月以内（採択発表日から16か月以内）","contact":"コールバック予約システムによる事前予約制","official_url":"https://shinjigyou-shinshutsu.smrj.go.jp/","pdf_source":"https://shinjigyou-shinshutsu.smrj.go.jp/docs/shinjigyou_koubo_3.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SHINJIGYO-03';

-- 3. SEICHOU-KASOKU-02: 中小企業成長加速化補助金（2次公募）90→95
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業成長加速化補助金（2次公募）","version":"2次公募（令和7年12月26日公開）","subsidy_overview":{"summary":"売上高100億円を目指す成長志向型の中小企業の大規模投資を支援する補助金","purpose":"中小企業の売上高100億円超への成長を加速"},"subsidy_amount":{"max":"5億円","min":"1億円（投資額要件）","note":"建物費・機械装置費・ソフトウェア費の合算で1億円以上が必要"},"subsidy_rate":"1/2","target_requirements":{"business_type":"中小企業者（中小企業等経営強化法第2条第1項）","sales_requirement":"売上高10億円以上100億円未満","investment_requirement":"補助対象経費のうち投資額1億円以上（税抜き）","declaration":"100億宣言ポータルサイトに宣言が公表済みであること","wage_up":"従業員1人当たり給与支給総額を年平均4.5%以上上昇させる計画","income_limit":"過去3年の課税所得の年平均額が15億円を超えないこと","exclusions":"みなし大企業、暴力団関係、風俗営業は対象外"},"eligible_expenses":["建物費（建設・増築・改修・中古建物取得等）","機械装置費（購入・製作・借用・改良等）","ソフトウェア費（専用ソフト購入・構築・クラウドサービス利用等）","外注費（加工・設計・検査等）","専門家経費（技術指導・助言）"],"application_period":{"start":"令和8年2月24日（火）","deadline":"令和8年3月26日（木）15:00まで"},"application_method":"jGrants電子申請（GビズIDプライムアカウント必要）","review_points":["経営力（100億円に向けたビジョン・事業戦略・付加価値増加率・賃上げ計画）","波及効果（サプライチェーン・地域経済・パートナーシップ構築宣言・BCP）","実現可能性（経営体制・財務状況・金融機関のコミットメント確認書）"],"business_period":"交付決定日から24か月以内","contact":{"phone":"0570-07-4153","ip_phone":"03-4446-4307","hours":"平日10:00-17:00","operator":"TOPPAN株式会社内"},"official_url":"https://growth-100-oku.smrj.go.jp/","pdf_source":"https://growth-100-oku.smrj.go.jp/documents/subsidy/2nd_kobo.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SEICHOU-KASOKU-02';

-- 4. MONODUKURI-23: ものづくり補助金 第23次（製品・サービス高付加価値化枠）90→95
UPDATE subsidy_cache SET detail_json = json('{"title":"ものづくり・商業・サービス生産性向上促進補助金（第23次公募）","version":"第23次公募（2026年2月6日公開）","subsidy_overview":{"summary":"中小企業等が制度変更に対応するため、生産性向上に資する革新的な新製品・新サービス開発等を行う事業を支援","purpose":"生産性向上と賃上げの実現"},"subsidy_amount":{"product_service_track":[{"employees":"1～5人","max":"750万円"},{"employees":"6～20人","max":"1,000万円"},{"employees":"21～50人","max":"1,500万円"},{"employees":"51人以上","max":"2,500万円"}],"wage_up_bonus":"最大100万円～1,000万円を上限に加算","note":"大幅な賃上げ特例適用時"},"subsidy_rate":{"sme":"1/2","small_scale":"2/3","minimum_wage_special":"2/3"},"target_requirements":{"business_type":"日本国内に本社及び実施場所を有する中小企業者等","employees":"常時使用する従業員1人以上","categories":["中小企業者","小規模企業者・小規模事業者","特定事業者の一部","特定非営利活動法人","社会福祉法人"],"business_plan":"付加価値額年平均3%増加、給与支給総額年平均3.5%増加等の3～5年事業計画を策定"},"eligible_expenses":{"required":"機械装置・システム構築費（単価50万円税抜き以上が必要）","optional":["技術導入費","専門家経費","運搬費","クラウドサービス利用費","原材料費","外注費","知的財産権等関連経費"]},"application_period":{"start":"2026年2月6日（金）","acceptance_start":"2026年4月3日（金）17:00","deadline":"2026年5月8日（金）17:00厳守"},"application_method":"GビズIDプライムアカウントによる電子申請のみ","review_points":["補助事業の適格性","経営力（経営目標の具体性・戦略性）","事業性（付加価値創出・賃上げ目標の実現可能性）","実現可能性（技術力・実施体制・資金調達）","政策面（地域経済波及・DX・低炭素技術活用）","口頭審査（オンライン実施）"],"business_period":{"product_service":"交付決定日から10か月以内（採択発表日から12か月後まで）","global":"交付決定日から12か月以内（採択発表日から14か月後まで）"},"contact":{"phone":"050-3821-7013","hours":"10:00～17:00（土日祝・年末年始除く）"},"official_url":"https://portal.monodukuri-hojo.jp/","pdf_source":"https://portal.monodukuri-hojo.jp/common/bunsho/ippan/23th/%E5%85%AC%E5%8B%9F%E8%A6%81%E9%A0%98_23%E6%AC%A1%E7%B7%A0%E5%88%87_20260206.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'MONODUKURI-23';

-- 5. MONODUKURI-GLOBAL: ものづくり補助金 グローバル枠 90→95
UPDATE subsidy_cache SET detail_json = json('{"title":"ものづくり・商業・サービス生産性向上促進補助金 グローバル枠（第23次公募）","version":"第23次公募（2026年2月6日公開）","subsidy_overview":{"summary":"中小企業等が海外需要開拓のため、革新的な新製品・新サービスの開発・海外展開を行う事業を支援","purpose":"海外市場への進出による生産性向上"},"subsidy_amount":{"max":"3,000万円","wage_up_bonus":"最大1,000万円加算（大幅賃上げ特例適用時）"},"subsidy_rate":{"sme":"1/2","small_scale":"2/3"},"target_requirements":{"business_type":"日本国内に本社及び実施場所を有する中小企業者等","employees":"常時使用する従業員1人以上","business_plan":"付加価値額年平均3%増加、給与支給総額年平均3.5%増加等の3～5年事業計画を策定","overseas":"海外事業の拡大・強化に向けた事業計画を有すること"},"eligible_expenses":{"required":"機械装置・システム構築費（単価50万円税抜き以上）","optional":["技術導入費","専門家経費","運搬費","クラウドサービス利用費","原材料費","外注費","知的財産権等関連経費"],"global_only":["海外旅費","通訳・翻訳費","広告宣伝・販売促進費"]},"application_period":{"start":"2026年2月6日（金）","acceptance_start":"2026年4月3日（金）17:00","deadline":"2026年5月8日（金）17:00厳守"},"business_period":"交付決定日から12か月以内（採択発表日から14か月後まで）","contact":{"phone":"050-3821-7013","hours":"10:00～17:00（土日祝・年末年始除く）"},"official_url":"https://portal.monodukuri-hojo.jp/","pdf_source":"https://portal.monodukuri-hojo.jp/common/bunsho/ippan/23th/%E5%85%AC%E5%8B%9F%E8%A6%81%E9%A0%98_23%E6%AC%A1%E7%B7%A0%E5%88%87_20260206.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'MONODUKURI-GLOBAL';

-- 6. JIGYOSHOKEI-MA-14: 事業承継・M&A補助金（14次公募）90→95
UPDATE subsidy_cache SET detail_json = json('{"title":"事業承継・M&A補助金（14次公募）","version":"14次公募（2026年1月30日公開）","subsidy_overview":{"summary":"事業承継やM&Aに際して設備投資等を行う中小企業者を支援する補助金。事業承継促進枠・専門家活用枠・PMI推進枠・廃業再チャレンジ枠の4枠","purpose":"事業承継・M&Aによる経営資源の円滑な引継ぎ支援"},"subsidy_amount":{"succession_track":{"base":"800万円","with_wage_up":"1,000万円","with_closure":"+300万円まで上乗せ可","note":"800万円超～1,000万円部分の補助率は1/2"},"expert_track":"600万円","pmi_track":"800万円（賃上げ時1,000万円）","closure_track":"150万円"},"subsidy_rate":{"small_scale":"2/3以内","other_sme":"1/2以内"},"target_requirements":{"business_type":"日本国内に拠点・居住地を持ち国内で事業を営む中小企業者等","individual":"個人事業主は青色申告者に限る","succession_condition":"被承継者から承継予定者への実質的な経営資源の引継ぎ","successor_requirement":"役員3年以上・雇用3年以上・親族等のいずれか","exclusions":"暴力団等の反社会的勢力"},"eligible_expenses":{"business":["設備費","産業財産権等関連経費","謝金","旅費","外注費","委託費"],"closure":["廃業支援費","在庫廃棄費","解体費","原状回復費","リース解約費","土壌汚染調査費","移転・移設費"]},"application_period":{"start":"2026年2月27日（金）","deadline":"2026年4月3日（金）17:00厳守"},"application_method":"jGrants電子申請（GビズIDプライムアカウント必要）","contact":{"phone":"050-3192-6274","hours":"9:30～12:00、13:00～17:00（土日祝除く）"},"official_url":"https://shoukei-mahojokin.go.jp/r6h/","pdf_source":"https://shoukei-mahojokin.go.jp/assets/documents/r7h/14-succession/requirements_succession_14.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'JIGYOSHOKEI-MA-14';

-- 7. IT-SUBSIDY-2026-TSUJYO: デジタル化・AI導入補助金2026 通常枠（名称変更反映）
UPDATE subsidy_cache SET detail_json = json('{"title":"デジタル化・AI導入補助金2026 通常枠（旧：IT導入補助金 通常枠）","version":"令和6年度補正予算（2026年1月23日概要公開）","subsidy_overview":{"summary":"中小企業・小規模事業者が自社の課題やニーズに合ったITツールを導入するための経費を一部補助し、労働生産性の向上を支援する制度。2026年度より名称をデジタル化・AI導入補助金に変更","purpose":"ITツール導入による労働生産性向上とデジタル化推進"},"subsidy_amount":{"range":"5万円～450万円","process_1":"1プロセス以上: 5万円以上150万円未満","process_4":"4プロセス以上: 150万円以上450万円以下"},"subsidy_rate":{"normal":"1/2以内","minimum_wage_special":"2/3以内（最低賃金引上げ特例）"},"target_requirements":{"business_type":"中小企業・小規模事業者等","minimum_wage_special":"令和6年10月～令和7年9月の間で3か月以上、地域別最低賃金未満の従業員が全従業員の30%以上"},"eligible_expenses":{"required":"ソフトウェア購入費（1種類以上の業務プロセスを保有するソフトウェア）","cloud":"クラウド利用料（最大2年分）","optional":["機能拡張","データ連携ツール","セキュリティ","導入コンサルティング・活用コンサルティング","導入設定・マニュアル設定・導入研修","保守サポート"]},"application_method":"GビズIDプライムアカウントによる電子申請","contact":{"url":"https://it-shien.smrj.go.jp/"},"official_url":"https://it-shien.smrj.go.jp/applicant/subsidy/normal/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_it.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'IT-SUBSIDY-2026-TSUJYO';

-- 8. IT-SUBSIDY-2026-DENSHI: デジタル化・AI導入補助金2026 デジタル基盤導入枠（新設枠）
UPDATE subsidy_cache SET detail_json = json('{"title":"デジタル化・AI導入補助金2026 デジタル基盤導入枠（旧：IT導入補助金から新設）","version":"令和6年度補正予算（2026年新設）","subsidy_overview":{"summary":"生産性向上に資するAI・ERP等の高機能ソフトウェア導入を支援する新設枠。従来のIT導入補助金から進化し、AI活用によるDX推進を重点支援","purpose":"AI・ERP等の高機能ソフトウェア導入による高度なデジタル化"},"subsidy_amount":{"max":"500万円"},"subsidy_rate":"2/3以内","target_requirements":{"business_type":"中小企業・小規模事業者等"},"eligible_expenses":["AI・ERP等の高機能ソフトウェア","クラウド利用料（最大2年分）","導入関連費"],"application_method":"GビズIDプライムアカウントによる電子申請","contact":{"url":"https://it-shien.smrj.go.jp/"},"official_url":"https://it-shien.smrj.go.jp/applicant/subsidy/digitalbase/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_it.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'IT-SUBSIDY-2026-DENSHI';

-- 9. IT-SUBSIDY-2026-INVOICE: デジタル化・AI導入補助金2026 インボイス枠
UPDATE subsidy_cache SET detail_json = json('{"title":"デジタル化・AI導入補助金2026 インボイス枠（旧：IT導入補助金 インボイス枠）","version":"令和6年度補正予算","subsidy_overview":{"summary":"インボイス制度への対応を目的としたITツール（会計・受発注・決済ソフト）及びハードウェアの導入を支援","purpose":"インボイス制度対応のためのデジタル化支援"},"subsidy_amount":{"invoice_type":{"max":"350万円","under_50":"50万円以下の部分","over_50":"50万円～350万円の部分"},"electronic_type":{"max":"350万円"}},"subsidy_rate":{"invoice_under_50_sme":"3/4以内","invoice_under_50_small":"4/5以内","invoice_over_50":"2/3以内","electronic":"2/3以内"},"target_requirements":{"business_type":"中小企業・小規模事業者等"},"eligible_expenses":{"invoice_type":["会計ソフト","受発注ソフト","決済ソフト","PC・タブレット","レジ・券売機等のハードウェア"],"electronic_type":["受発注ソフト（電子取引目的）"]},"application_method":"GビズIDプライムアカウントによる電子申請","contact":{"url":"https://it-shien.smrj.go.jp/"},"official_url":"https://it-shien.smrj.go.jp/applicant/subsidy/digitalbased_invoice/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_it.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'IT-SUBSIDY-2026-INVOICE';

-- 10. IT-SUBSIDY-2026-SECURITY: デジタル化・AI導入補助金2026 セキュリティ対策推進枠
UPDATE subsidy_cache SET detail_json = json('{"title":"デジタル化・AI導入補助金2026 セキュリティ対策推進枠（旧：IT導入補助金 セキュリティ対策推進枠）","version":"令和6年度補正予算","subsidy_overview":{"summary":"サイバー攻撃の増加に伴い、中小企業のセキュリティ対策の強化を支援する枠","purpose":"中小企業のサイバーセキュリティ対策強化"},"subsidy_amount":{"min":"5万円","max":"100万円"},"subsidy_rate":"1/2以内","target_requirements":{"business_type":"中小企業・小規模事業者等"},"eligible_expenses":["セキュリティサービス利用料（最大2年分）"],"application_method":"GビズIDプライムアカウントによる電子申請","contact":{"url":"https://it-shien.smrj.go.jp/"},"official_url":"https://it-shien.smrj.go.jp/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_it.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'IT-SUBSIDY-2026-SECURITY';

-- 11. IT-SUBSIDY-2026-FUKUSU: デジタル化・AI導入補助金2026 複数社連携IT導入枠
UPDATE subsidy_cache SET detail_json = json('{"title":"デジタル化・AI導入補助金2026 複数社連携IT導入枠（旧：IT導入補助金 複数社連携IT導入枠）","version":"令和6年度補正予算","subsidy_overview":{"summary":"複数の中小企業が連携してITツールを導入し、サプライチェーン全体の効率化や地域課題の解決を支援する枠","purpose":"複数社連携によるIT導入とサプライチェーン効率化"},"subsidy_amount":{"max":"3,000万円"},"subsidy_rate":{"base":"1/2以内","some_components":"2/3以内（連携コンポーネントにより異なる）"},"target_requirements":{"business_type":"中小企業・小規模事業者等（複数社での連携申請）"},"eligible_expenses":["複数の中小企業が連携したITツールの導入費","基盤導入関連費"],"application_method":"GビズIDプライムアカウントによる電子申請","contact":{"url":"https://it-shien.smrj.go.jp/"},"official_url":"https://it-shien.smrj.go.jp/applicant/subsidy/digitalbased_multiple_companies/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_it.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'IT-SUBSIDY-2026-FUKUSU';

-- 12. SHINJIGYO-MONO-2026: 新事業進出＋ものづくり統合情報 90→95
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業新事業進出補助金・ものづくり補助金 統合ガイド（2026年度）","version":"2026年度最新","subsidy_overview":{"summary":"2026年度は中小企業新事業進出補助金とものづくり補助金が並行実施。新事業進出は第3回公募中、ものづくりは第23次公募。将来的に統合の方向性あり","purpose":"中小企業の設備投資・新事業進出・生産性向上を総合的に支援"},"programs":[{"name":"中小企業新事業進出促進補助金（第3回）","max":"9,000万円（賃上げ特例・101人以上）","rate":"1/2","deadline":"令和8年3月26日18:00","url":"https://shinjigyou-shinshutsu.smrj.go.jp/"},{"name":"ものづくり補助金（第23次）","max":"2,500万円（製品・サービス枠・51人以上）/ 3,000万円（グローバル枠）","rate":"1/2（小規模2/3）","deadline":"2026年5月8日17:00","url":"https://portal.monodukuri-hojo.jp/"},{"name":"中小企業成長加速化補助金（2次）","max":"5億円","rate":"1/2","deadline":"令和8年3月26日15:00","url":"https://growth-100-oku.smrj.go.jp/"}],"key_differences":"新事業進出は新市場への進出が必須、ものづくりは革新的製品・サービス開発、成長加速化は売上10億以上100億未満の企業向け","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SHINJIGYO-MONO-2026';
