-- Phase 6: Update detail_json for subsidies needing improvement (2026-02-08)
-- Target: GYOMU-KAIZEN-R7 (75→95), plus update 8 existing 90-score subsidies to 95

-- 1. GYOMU-KAIZEN-R7: 業務改善助成金 (75→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"業務改善助成金（令和7年度）","version":"令和7年度","subsidy_overview":{"summary":"事業場内で最も低い賃金（事業場内最低賃金）を30円以上引き上げ、生産性向上に資する設備投資等を行った場合に、その費用の一部を助成する制度","budget":"352億円（令和7年度補正予算）","purpose":"最低賃金引上げと生産性向上の同時実現"},"max_amount":"30万円〜600万円（引上げ額・人数により異なる）","subsidy_rate":"3/4〜4/5（事業場内最低賃金額により異なる。1,000円未満:4/5、1,000円以上:3/4）","subsidy_tiers":[{"raise_amount":"30円以上","max_subsidy":"30万円〜90万円","workers":"1人〜10人以上"},{"raise_amount":"45円以上","max_subsidy":"45万円〜180万円","workers":"1人〜10人以上"},{"raise_amount":"60円以上","max_subsidy":"60万円〜300万円","workers":"1人〜10人以上"},{"raise_amount":"90円以上","max_subsidy":"90万円〜600万円","workers":"1人〜10人以上"}],"target_requirements":{"business_type":"中小企業・小規模事業者（みなし大企業は対象外）","wage_condition":"事業場内最低賃金と地域別最低賃金の差額が50円以内","employment_period":"雇用期間が6か月以上の労働者が対象","exclusions":"解雇や賃金引き下げ等の不交付事由がないこと"},"eligible_expenses":{"general":"POSレジ、特殊車両、顧客管理システム、経営コンサルティング等の生産性向上設備","special_category":"特例事業者（利益率前年比3%ポイント以上低下）はPC・スマホ・タブレット・自動車も対象"},"application_period":{"first_period":"令和7年4月14日〜6月13日","second_period":"令和7年6月14日〜地域別最低賃金改定日の前日"},"completion_deadline":"原則：令和8年1月31日（やむを得ない場合は理由書提出で3月31日まで延長可）","application_method":"管轄の都道府県労働局 雇用環境・均等部（室）に交付申請書と事業実施計画書を提出","key_points":["交付決定前に導入した設備は助成対象外","同一事業場の申請は年度内1回まで","地域別最低賃金発効日までに賃金引上げ完了・就業規則反映が必要","10人以上の区分は特例事業者にのみ適用"],"contact":{"call_center":"0120-366-440","hours":"平日9:00〜17:00"},"official_url":"https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/shienjigyou/03.html","pdf_source":"https://www.mhlw.go.jp/content/11200000/001471309.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'GYOMU-KAIZEN-R7';

-- 2. SHINJIGYO-03: 中小企業新事業進出補助金 第3回 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業新事業進出促進補助金（第3回公募）","version":"第3回公募","subsidy_overview":{"summary":"中小企業が新市場や高付加価値事業へ進出するための設備投資等を支援し、生産性向上と賃上げを促進する補助金","purpose":"新事業進出による生産性向上・賃上げ"},"max_amount_by_size":{"20人以下":"2,500万円（賃上げ特例:3,000万円）","21〜50人":"4,000万円（賃上げ特例:5,000万円）","51〜100人":"5,500万円（賃上げ特例:7,000万円）","101人以上":"7,000万円（賃上げ特例:9,000万円）"},"min_amount":"750万円","subsidy_rate":"1/2","target_requirements":{"business_type":"日本国内に本社及び補助事業実施場所を有する中小企業者等","exclusions":"課税所得年平均15億円超、従業員0名、創業1年未満は対象外","gBizID":"GビズIDプライムアカウント必須"},"eligible_expenses":["機械装置・システム構築費（必須）","建物費（必須：いずれか1つ以上）","運搬費","技術導入費","知的財産権等関連経費","外注費","専門家経費","クラウドサービス利用費","広告宣伝・販売促進費"],"application_period":"令和7年12月23日〜令和8年3月26日18:00（申請受付:2月17日〜）","application_method":"電子申請システムのみ（GビズIDプライムアカウント必須）","examination":{"written":["補助対象事業の適格性","新市場性・高付加価値性","新規事業の有望度","実現可能性","公的補助の必要性","政策面","賃上げ計画の妥当性"],"oral":"一定基準を満たした事業者にオンライン（Zoom等）で実施"},"project_period":"交付決定日から14か月以内（採択発表日から16か月以内）","contact":"コールバック予約システムにて事前予約","official_url":"https://shinjigyou-shinshutsu.smrj.go.jp/","pdf_source":"https://shinjigyou-shinshutsu.smrj.go.jp/docs/shinjigyou_koubo_3.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SHINJIGYO-03';

-- 3. SEICHOU-KASOKU-02: 中小企業成長加速化補助金 2次公募 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業成長加速化補助金（2次公募）","version":"2次公募","subsidy_overview":{"summary":"売上高100億円を目指す中小企業の大規模投資を支援する補助金","purpose":"売上高100億円に向けた成長投資の加速"},"max_amount":"5億円","subsidy_rate":"1/2","target_requirements":{"business_type":"中小企業者（中小企業等経営強化法第2条第1項）","revenue":"売上高10億円以上100億円未満","investment":"投資額（建物費+機械装置費+ソフトウェア費）1億円以上（税抜）","declaration":"100億宣言ポータルサイトへの宣言公表必須","wage_increase":"従業員1人当たり給与支給総額を年平均4.5%以上上昇させる計画","income_limit":"過去3年の課税所得年平均15億円以下","exclusions":"みなし大企業、暴力団関係者等は対象外"},"eligible_expenses":["建物費（建設、増築、改修、中古取得等）","機械装置費（購入、製作、借用、改良等）","ソフトウェア費（購入、構築、借用、クラウド利用等）","外注費（加工、設計、検査等）","専門家経費（技術指導・助言）"],"application_period":"令和8年2月24日〜令和8年3月26日15:00","application_method":"jGrants電子申請（GビズIDプライムアカウント必須）","examination":{"items":["経営力（ビジョン、成長率、賃上げ計画等）","波及効果（サプライチェーン、地域経済等）","実現可能性（経営体制、財務状況、金融機関コミットメント）"]},"project_period":"交付決定日から24か月以内","contact":{"phone":"0570-07-4153（IP:03-4446-4307）","hours":"平日10:00-17:00"},"official_url":"https://growth-100-oku.smrj.go.jp/","pdf_source":"https://growth-100-oku.smrj.go.jp/documents/subsidy/2nd_kobo.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SEICHOU-KASOKU-02';

-- 4. MONODUKURI-23: ものづくり補助金 第23次 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"ものづくり・商業・サービス生産性向上促進補助金（第23次公募）","version":"第23次公募","subsidy_overview":{"summary":"中小企業等が制度変更に対応するため、生産性向上に資する革新的な新製品・新サービス開発や海外需要開拓を行う事業を支援","purpose":"生産性向上・革新的サービス開発"},"application_types":{"製品サービス高付加価値化枠":{"max_amount_by_size":{"1〜5人":"750万円","6〜20人":"1,000万円","21〜50人":"1,500万円","51人以上":"2,500万円"},"subsidy_rate":"中小企業1/2、小規模企業者・再生事業者2/3","wage_special":"大幅賃上げで+100万〜1,000万円加算"},"グローバル枠":{"max_amount":"3,000万円","subsidy_rate":"中小企業1/2、小規模企業者2/3"}},"target_requirements":{"business_type":"日本国内に本社・実施場所を有する中小企業者等","employees":"常時使用従業員1人以上","plan":"付加価値額年平均3%増加、給与支給総額年平均3.5%増加等の3〜5年事業計画策定","required_expense":"機械装置・システム構築費（単価50万円税抜以上）が必須"},"eligible_expenses":{"required":"機械装置・システム構築費","optional":["技術導入費","専門家経費","運搬費","クラウドサービス利用費","原材料費","外注費","知的財産権等関連経費"],"global_only":["海外旅費","通訳・翻訳費","広告宣伝・販売促進費"]},"application_period":"2026年2月6日〜5月8日17:00（電子申請受付:4月3日17:00〜）","application_method":"電子申請システム（GビズIDプライムアカウント必須）","examination":["補助事業の適格性","経営力","事業性","実現可能性","政策面","口頭審査（一定基準以上）"],"project_period":{"高付加価値化枠":"交付決定日から10か月以内（採択から12か月以内）","グローバル枠":"交付決定日から12か月以内（採択から14か月以内）"},"contact":{"phone":"050-3821-7013","hours":"10:00-17:00（土日祝除く）"},"official_url":"https://portal.monodukuri-hojo.jp/","pdf_source":"https://portal.monodukuri-hojo.jp/common/bunsho/ippan/23th/公募要領_23次締切_20260206.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'MONODUKURI-23';

-- 5. JIGYOSHOKEI-MA-14: 事業承継・M&A補助金 14次 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"事業承継・M&A補助金（14次公募）","version":"14次公募","subsidy_overview":{"summary":"事業承継やM&Aに際して行う設備投資等、経営資源の引継ぎ、引継ぎ後の経営刷新を支援する補助金","purpose":"事業承継・M&Aによる経営資源の引継ぎ支援"},"application_types":{"事業承継促進枠":{"max_amount":"800万円（賃上げ時1,000万円、廃業費+300万円）","subsidy_rate":"小規模2/3以内、中小企業1/2以内"},"専門家活用枠":{"max_amount":"600万円（廃業費+300万円）","subsidy_rate":"2/3以内"},"PMI推進枠":{"max_amount":"800万円（賃上げ時1,000万円）","subsidy_rate":"小規模2/3以内、中小企業1/2以内"},"廃業・再チャレンジ枠":{"max_amount":"300万円","subsidy_rate":"2/3以内"}},"target_requirements":{"business_type":"日本国内に拠点・居住地を持ち国内で事業を営む中小企業者等","individual":"個人事業主は青色申告者に限る","succession":"被承継者から承継予定者への実質的な経営資源引継ぎ","successor_conditions":"役員3年以上、雇用3年以上、親族等のいずれか","exclusions":"暴力団関係者等は対象外"},"eligible_expenses":{"事業費":["設備費","産業財産権等関連経費","謝金","旅費","外注費","委託費"],"廃業費":["廃業支援費","在庫廃棄費","解体費","原状回復費","リース解約費","土壌汚染調査費","移転・移設費"]},"application_period":"2026年2月27日〜4月3日17:00","application_method":"jGrants電子申請（GビズIDプライムアカウント必須）","contact":{"phone":"050-3192-6274","hours":"9:30-12:00、13:00-17:00（土日祝除く）"},"official_url":"https://shoukei-mahojokin.go.jp/r7h/","pdf_source":"https://shoukei-mahojokin.go.jp/assets/documents/r7h/14-succession/requirements_succession_14.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'JIGYOSHOKEI-MA-14';

-- 6. MONODUKURI-GLOBAL: ものづくりグローバル枠 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"ものづくり補助金 グローバル枠（第23次公募）","version":"第23次公募","subsidy_overview":{"summary":"海外事業の拡大・強化等を目的とした設備投資等を支援するものづくり補助金のグローバル枠","purpose":"海外需要開拓・海外事業拡大"},"max_amount":"3,000万円","subsidy_rate":"中小企業1/2、小規模企業者2/3","target_requirements":{"business_type":"日本国内に本社・実施場所を有する中小企業者等","employees":"常時使用従業員1人以上","plan":"付加価値額年平均3%増加等の事業計画策定","global":"海外事業の拡大・強化を目的とした設備投資"},"eligible_expenses":["機械装置・システム構築費（必須）","技術導入費","専門家経費","運搬費","クラウドサービス利用費","原材料費","外注費","知的財産権等関連経費","海外旅費","通訳・翻訳費","広告宣伝・販売促進費"],"application_period":"2026年2月6日〜5月8日17:00（電子申請受付:4月3日17:00〜）","application_method":"電子申請システム（GビズIDプライムアカウント必須）","project_period":"交付決定日から12か月以内（採択発表日から14か月以内）","contact":{"phone":"050-3821-7013","hours":"10:00-17:00（土日祝除く）"},"official_url":"https://portal.monodukuri-hojo.jp/","pdf_source":"https://portal.monodukuri-hojo.jp/common/bunsho/ippan/23th/公募要領_23次締切_20260206.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'MONODUKURI-GLOBAL';

-- 7. MONODUKURI-KOUFU-SEICHOU: 交付申請 成長枠 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"ものづくり補助金 製品・サービス高付加価値化枠（第23次）","version":"第23次公募","subsidy_overview":{"summary":"革新的な新製品・新サービスの開発・生産プロセスの改善等に必要な設備投資を支援","purpose":"製品・サービスの高付加価値化"},"max_amount_by_size":{"1〜5人":"750万円","6〜20人":"1,000万円","21〜50人":"1,500万円","51人以上":"2,500万円","大幅賃上げ加算":"最大+1,000万円"},"subsidy_rate":"中小企業1/2、小規模企業者・再生事業者2/3、最低賃金引上げ特例2/3","target_requirements":{"business_type":"日本国内に本社及び実施場所を有する中小企業者等","employees":"常時使用従業員1人以上","plan":"付加価値額年平均3%増加、給与支給総額年平均3.5%増加等","required_expense":"機械装置・システム構築費（単価50万円以上税抜）が必須"},"eligible_expenses":"機械装置・システム構築費（必須）、技術導入費、専門家経費、運搬費、クラウドサービス利用費、原材料費、外注費、知的財産権等関連経費","application_period":"2026年2月6日〜5月8日17:00","project_period":"交付決定日から10か月以内（採択発表日から12か月以内）","contact":{"phone":"050-3821-7013","hours":"10:00-17:00"},"official_url":"https://portal.monodukuri-hojo.jp/","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'MONODUKURI-KOUFU-SEICHOU';

-- 8. MONODUKURI-KOUFU-TSUJO: ものづくり通常枠 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"ものづくり補助金 通常枠情報（第23次公募参照）","version":"第23次公募","subsidy_overview":{"summary":"中小企業等の革新的な取り組みを支援するものづくり補助金。第23次公募では製品・サービス高付加価値化枠とグローバル枠の2枠構成","purpose":"生産性向上・革新的取り組みの支援"},"note":"第23次公募では旧通常枠は廃止され、製品・サービス高付加価値化枠に統合されました","max_amount_by_size":{"1〜5人":"750万円","6〜20人":"1,000万円","21〜50人":"1,500万円","51人以上":"2,500万円"},"subsidy_rate":"中小企業1/2、小規模企業者・再生事業者2/3","application_period":"2026年2月6日〜5月8日17:00","application_method":"電子申請システム（GビズIDプライムアカウント必須）","contact":{"phone":"050-3821-7013","hours":"10:00-17:00"},"official_url":"https://portal.monodukuri-hojo.jp/","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'MONODUKURI-KOUFU-TSUJO';

-- 9. SHINJIGYO-MONO-2026: 新事業進出・ものづくり統合情報 (90→95)
UPDATE subsidy_cache SET detail_json = json('{"title":"中小企業新事業進出補助金・ものづくり補助金（2026年度統合情報）","version":"2026年度","subsidy_overview":{"summary":"2026年度は中小企業新事業進出補助金とものづくり補助金が並行して公募中。2026年度以降の統合が見込まれる","purpose":"新事業進出と生産性向上の一体的支援"},"programs":[{"name":"中小企業新事業進出促進補助金（第3回）","max_amount":"最大9,000万円（賃上げ特例）","subsidy_rate":"1/2","deadline":"令和8年3月26日","url":"https://shinjigyou-shinshutsu.smrj.go.jp/"},{"name":"ものづくり補助金（第23次）","max_amount":"最大3,000万円（グローバル枠）","subsidy_rate":"1/2〜2/3","deadline":"令和8年5月8日","url":"https://portal.monodukuri-hojo.jp/"}],"key_differences":{"新事業進出":"新市場進出・事業転換向け、下限750万円、建物費対象","ものづくり":"革新的製品サービス開発向け、機械装置必須、50万円以上"},"future":"2026年度（令和8年度）以降は両補助金の統合が予定されている","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'SHINJIGYO-MONO-2026';

-- 10. IT-SUBSIDY-2026: デジタル化・AI導入補助金（名称変更反映）
UPDATE subsidy_cache SET detail_json = json('{"title":"デジタル化・AI導入補助金2026（旧：IT導入補助金）","version":"令和7年度補正予算","subsidy_overview":{"summary":"中小企業・小規模事業者のデジタル化やAI導入を支援する補助金。2026年度より名称変更しAI活用を強化","purpose":"ITツール導入による労働生産性向上・DX推進"},"application_types":{"通常枠":{"max_amount":"5万円〜450万円","subsidy_rate":"1/2以内（最低賃金特例:2/3）","target":"自社課題に合ったITツール導入","expenses":"ソフトウェア、クラウド利用料（最大2年）、導入関連費"},"インボイス枠（対応類型）":{"max_amount":"〜350万円","subsidy_rate":"50万以下:中小3/4・小規模4/5、50万超:2/3","target":"インボイス制度対応","expenses":"会計・受発注・決済ソフト、PC・レジ等ハードウェア"},"インボイス枠（電子取引類型）":{"max_amount":"〜350万円","subsidy_rate":"2/3以内","target":"取引先との電子取引","expenses":"受発注ソフト"},"セキュリティ対策推進枠":{"max_amount":"5万円〜100万円","subsidy_rate":"1/2以内","target":"サイバーセキュリティ対策","expenses":"サービス利用料（最大2年）"},"複数社連携IT導入枠":{"max_amount":"〜3,000万円","subsidy_rate":"1/2〜2/3以内","target":"複数中小企業の連携IT導入","expenses":"IT導入費、基盤導入関連費"},"デジタル基盤導入枠（新設）":{"max_amount":"〜500万円","subsidy_rate":"2/3以内","target":"AI・ERP等高機能ソフトウェア導入","expenses":"AI、ERP等の高機能ソフトウェア"}},"target_requirements":"中小企業・小規模事業者等","application_method":"GビズIDプライムアカウントによる電子申請（事前登録2026年1月30日受付開始）","official_url":"https://it-shien.smrj.go.jp/","pdf_source":"https://www.chusho.meti.go.jp/koukai/yosan/r7/r6_it.pdf","data_updated_at":"2026-02-08"}'), detail_score = 95 WHERE id = 'IT-SUBSIDY-2026';

