-- Manual deep search Phase 2: broader keyword matching
-- Generated: 2026-02-09

-- 病児保育事業補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/69799c33-85cb-44f6-8c70-08ed3a292ab5/ef9b6009/20250910_policies_kosodateshien_houkago-jidou_70.pdf", "PDF_source": "https://www.cfa.go.jp/policies/kosodateshien/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/8f03ee44-b4a9-4206-a613-e0ecf72b380c/f3a2c4ef/20230401_policies_kosodateshien_jidoukan_05.pdf", "https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/e8ed78f7-9ff8-4c93-98ac-a9cb47c8a0dc/53196879/20250408_policies_kosodateshien_jidou-fukushi-shuukan_20.pdf", "https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/69799c33-85cb-44f6-8c70-08ed3a292ab5/929840ee/20230401_policies_kosodateshien_houkago-jidou_18.pdf", "https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/69799c33-85cb-44f6-8c70-08ed3a292ab5/ef9b6009/20250910_policies_kosodateshien_houkago-jidou_70.pdf", "https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/e8ed78f7-9ff8-4c93-98ac-a9cb47c8a0dc/56d44692/20250408_policies_kosodateshien_jidou-fukushi-shuukan_21.pdf"]}'), cached_at = datetime('now') WHERE id = 'BYOUJI-HOIKU';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('BYOUJI-HOIKU', 'https://www.cfa.go.jp/assets/contents/node/basic_page/field_ref_resources/69799c33-85cb-44f6-8c70-08ed3a292ab5/ef9b6009/20250910_policies_kosodateshien_houkago-jidou_70.pdf', 'https://www.cfa.go.jp/policies/kosodateshien/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), '病児保育事業補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- 文化芸術活動基盤強化事業（文化庁）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.bunka.go.jp/shinsei_boshu/kojinjohohogo/pdf/1392997_01.pdf", "PDF_source": "https://www.bunka.go.jp/shinsei_boshu/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.bunka.go.jp/seisaku/geijyutu_katsudou/pdf/94285301_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/shogai/pdf/ruby_nashi.pdf", "https://www.bunka.go.jp/shinsei_boshu/kojinjohohogo/pdf/1392997_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kojinjohohogo/pdf/1392997_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/kojinjohohogo/pdf/1392997_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'BUNKA-GEIJUTSU';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('BUNKA-GEIJUTSU', 'https://www.bunka.go.jp/shinsei_boshu/kojinjohohogo/pdf/1392997_01.pdf', 'https://www.bunka.go.jp/shinsei_boshu/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), '文化芸術活動基盤強化事業（文化庁） 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- 茶・果樹産地構造改革事業
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-200.pdf", "PDF_source": "https://www.maff.go.jp/j/seisan/tokusan/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-174.pdf", "https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-201.pdf", "https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-171.pdf", "https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-200.pdf", "https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-203.pdf"]}'), cached_at = datetime('now') WHERE id = 'CHA-KAJU-KAIKAKU';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('CHA-KAJU-KAIKAKU', 'https://www.maff.go.jp/j/seisan/sien/sizai/attach/pdf/service-200.pdf', 'https://www.maff.go.jp/j/seisan/tokusan/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), '茶・果樹産地構造改革事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- 住宅省エネキャンペーン2026
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.mlit.go.jp/jutakukentiku/house/content/001866113.pdf", "PDF_source": "https://www.mlit.go.jp/jutakukentiku/house/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.mlit.go.jp/jutakukentiku/house/content/001865512.pdf", "https://www.mlit.go.jp/jutakukentiku/house/content/001878966.pdf", "https://www.mlit.go.jp/jutakukentiku/house/content/001878962.pdf", "https://www.mlit.go.jp/jutakukentiku/house/content/001866220.pdf", "https://www.mlit.go.jp/jutakukentiku/house/content/001866113.pdf"]}'), cached_at = datetime('now') WHERE id = 'JUTAKU-ECO-POINT';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('JUTAKU-ECO-POINT', 'https://www.mlit.go.jp/jutakukentiku/house/content/001866113.pdf', 'https://www.mlit.go.jp/jutakukentiku/house/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), '住宅省エネキャンペーン2026 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- デジタル田園都市国家構想交付金（TYPE1〜3）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.chisou.go.jp/sousei/about/mirai/pdf/type1guidelines.pdf", "PDF_source": "https://www.chisou.go.jp/sousei/about/mirai/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.chisou.go.jp/sousei/about/mirai/pdf/digitalhandbook.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/01_koufuketteishiryou_r5hosei.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/teleworkguidelines.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/type1guidelines.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/type23guidelines.pdf"]}'), cached_at = datetime('now') WHERE id = 'DIGIDEN-KOUFUKIN';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('DIGIDEN-KOUFUKIN', 'https://www.chisou.go.jp/sousei/about/mirai/pdf/type1guidelines.pdf', 'https://www.chisou.go.jp/sousei/about/mirai/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), 'デジタル田園都市国家構想交付金（TYPE1〜3） 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- デジタル田園都市国家構想交付金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.chisou.go.jp/sousei/about/mirai/pdf/type1guidelines.pdf", "PDF_source": "https://www.chisou.go.jp/sousei/about/mirai/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.chisou.go.jp/sousei/about/mirai/pdf/digitalhandbook.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/01_koufuketteishiryou_r5hosei.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/teleworkguidelines.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/type1guidelines.pdf", "https://www.chisou.go.jp/sousei/about/mirai/pdf/type23guidelines.pdf"]}'), cached_at = datetime('now') WHERE id = 'DIGITAL-DENEN';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('DIGITAL-DENEN', 'https://www.chisou.go.jp/sousei/about/mirai/pdf/type1guidelines.pdf', 'https://www.chisou.go.jp/sousei/about/mirai/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), 'デジタル田園都市国家構想交付金 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- デジタル人材育成プラットフォーム（マナビDX・マナビDX Quest）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://manabi-dx.ipa.go.jp/contents/provider/manabidx_criteria.pdf", "PDF_source": "https://manabi-dx.ipa.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://manabi-dx.ipa.go.jp/contents/provider/manabidx_criteria.pdf"]}'), cached_at = datetime('now') WHERE id = 'DIGITAL-JINZAI';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('DIGITAL-JINZAI', 'https://manabi-dx.ipa.go.jp/contents/provider/manabidx_criteria.pdf', 'https://manabi-dx.ipa.go.jp/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), 'デジタル人材育成プラットフォーム（マナビDX・マナビDX Quest） 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- デジタル人材育成プラットフォーム事業（マナビDX等）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://manabi-dx.ipa.go.jp/contents/provider/manabidx_criteria.pdf", "PDF_source": "https://manabi-dx.ipa.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://manabi-dx.ipa.go.jp/contents/provider/manabidx_criteria.pdf"]}'), cached_at = datetime('now') WHERE id = 'DIGITAL-JINZAI-PF';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('DIGITAL-JINZAI-PF', 'https://manabi-dx.ipa.go.jp/contents/provider/manabidx_criteria.pdf', 'https://manabi-dx.ipa.go.jp/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), 'デジタル人材育成プラットフォーム事業（マナビDX等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- 地理的表示（GI）保護制度活用支援事業
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.maff.go.jp/j/shokusan/gi_act/outline/attach/pdf/index-211.pdf", "PDF_source": "https://www.maff.go.jp/j/shokusan/gi_act/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.maff.go.jp/j/shokusan/gi_act/process/attach/pdf/index-38.pdf", "https://www.maff.go.jp/j/shokusan/gi_act/process/attach/pdf/index-10.pdf", "https://www.maff.go.jp/j/shokusan/gi_act/outline/attach/pdf/index-29.pdf", "https://www.maff.go.jp/j/shokusan/gi_act/process/attach/pdf/index-37.pdf", "https://www.maff.go.jp/j/shokusan/gi_act/outline/attach/pdf/index-211.pdf"]}'), cached_at = datetime('now') WHERE id = 'GI-HOGO-SHIEN';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('GI-HOGO-SHIEN', 'https://www.maff.go.jp/j/shokusan/gi_act/outline/attach/pdf/index-211.pdf', 'https://www.maff.go.jp/j/shokusan/gi_act/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), '地理的表示（GI）保護制度活用支援事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- 循環型社会形成推進交付金（廃棄物処理施設整備）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.env.go.jp/recycle/waste/3r_network/2_koufu/koufu_youkou.pdf", "PDF_source": "https://www.env.go.jp/recycle/waste/3r_network/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www.env.go.jp/recycle/waste/3r_network/2_koufu/koufu_youkou.pdf", "https://www.env.go.jp/recycle/waste/3r_network/2_koufu_sen/2koufu_youkou.pdf", "https://www.env.go.jp/recycle/waste/3r_network/2_koufu/tori_yoryou.pdf"]}'), cached_at = datetime('now') WHERE id = 'JUNKAN-KOUFUKIN';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('JUNKAN-KOUFUKIN', 'https://www.env.go.jp/recycle/waste/3r_network/2_koufu/koufu_youkou.pdf', 'https://www.env.go.jp/recycle/waste/3r_network/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), '循環型社会形成推進交付金（廃棄物処理施設整備） 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- ムーンショット型研究開発事業
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www8.cao.go.jp/cstp/moonshot/ms_haihui073/jisshiyoryo.pdf", "PDF_source": "https://www8.cao.go.jp/cstp/moonshot/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page_broader", "all_koubo_pdfs": ["https://www8.cao.go.jp/cstp/moonshot/ms_haihui073/jisshiyoryo.pdf", "https://www8.cao.go.jp/cstp/moonshot/ms_haihui080/siryo1.pdf"]}'), cached_at = datetime('now') WHERE id = 'MOONSHOT-RD';
INSERT OR REPLACE INTO koubo_monitors (subsidy_id, koubo_pdf_url, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_at, last_crawl_result, next_crawl_at, fallback_search_query, created_at, updated_at) VALUES ('MOONSHOT-RD', 'https://www8.cao.go.jp/cstp/moonshot/ms_haihui073/jisshiyoryo.pdf', 'https://www8.cao.go.jp/cstp/moonshot/', 'sub_page_broader', 'monthly', 'active', datetime('now'), 'success', datetime('now', '+30 days'), 'ムーンショット型研究開発事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));

-- Not found: register as needs_manual for superadmin review
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('AMED-SOUYAKU', 'https://www.amed.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'AMED創薬支援推進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('IRYOU-KIKI-KAIHATSU', 'https://www.amed.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '医療機器開発支援事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('BLUE-CARBON', 'https://www.env.go.jp/water/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'ブルーカーボン生態系（藻場・干潟等）保全・再生事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('CHISUI-JIGYOU', 'https://www.mlit.go.jp/river/', 'not_found', 'monthly', 'needs_manual', 'not_found', '治水事業（河川改修・ダム・遊水池等の整備） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('CHINETSU-HATSUDEN', 'https://www.jogmec.go.jp/geothermal/', 'not_found', 'monthly', 'needs_manual', 'not_found', '地熱発電導入支援事業（地熱資源開発・発電所建設） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('CHOUKI-REFORM', 'https://www.mlit.go.jp/jutakukentiku/house/', 'not_found', 'monthly', 'needs_manual', 'not_found', '長期優良住宅化リフォーム推進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KODOMO-ECO-SUMAI', 'https://www.mlit.go.jp/jutakukentiku/house/', 'not_found', 'monthly', 'needs_manual', 'not_found', '子育てグリーン住宅支援事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('TAISHIN-SHINDAN-HOJO', 'https://www.mlit.go.jp/jutakukentiku/house/', 'not_found', 'monthly', 'needs_manual', 'not_found', '住宅・建築物耐震改修等事業（耐震診断義務化対象等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('CHOUKI-YURYOU-REFORM', 'https://www.kenken.go.jp/chouki_r/', 'not_found', 'monthly', 'needs_manual', 'not_found', '長期優良住宅化リフォーム推進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('CLOUD-SOKUSHIN', 'https://www.ismap.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'ISMAP（政府情報システムのためのセキュリティ評価制度） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('DIGITAL-TWIN', 'https://www.mlit.go.jp/plateau/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'デジタルツイン活用実証事業（PLATEAU等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('PLATEAU-3D', 'https://www.mlit.go.jp/plateau/', 'not_found', 'monthly', 'needs_manual', 'not_found', '3D都市モデル（PLATEAU）活用促進事業（デジタルツイン） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('FUKUSHI-SHARYO', 'https://www.wam.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '福祉車両購入費補助金（介護送迎用等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('GAIKOKUJIN-KANKYOU', 'https://www.moj.go.jp/isa/policies/coexistence/04_00017.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '外国人材受入れ環境整備交付金（一元的相談窓口等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('GAIKOKUJIN-UKEIRE', 'https://www.moj.go.jp/isa/policies/coexistence/index.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '外国人材受入・共生支援（特定技能・技能実習制度関連） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('GESUIDOU-KAIKAKU', 'https://www.mlit.go.jp/mizukokudo/sewerage/', 'not_found', 'monthly', 'needs_manual', 'not_found', '下水道施設改築推進事業（下水道長寿命化・脱炭素化） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('JOUSUIDOU-TAISHIN', 'https://www.mlit.go.jp/mizukokudo/sewerage/', 'not_found', 'monthly', 'needs_manual', 'not_found', '上下水道耐震化等推進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('GOUSETSU-TAISAKU', 'https://www.mlit.go.jp/kokudoseisaku/chirit/kokudoseisaku_chirit_tk_000060.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '豪雪地帯対策特別事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('GX-LEAGUE', 'https://gx-league.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'GXリーグ・GX経済移行債を活用した支援策 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('GIGA-SCHOOL', 'https://www.mext.go.jp/a_menu/other/index_00001.htm', 'not_found', 'monthly', 'needs_manual', 'not_found', 'GIGAスクール構想推進事業（1人1台端末更新等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('HOJOKIN-SHINSEI-DX', 'https://www.jgrants-portal.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '補助金申請DX推進事業（jGrants電子申請） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('INBOUND-KANKYOU', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', '訪日外国人旅行者受入環境整備補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('INBOUND-UKEIRE', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'インバウンド受入環境整備高度化事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KANKOU-KOUFUKACHI', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', '地域一体型観光サービス高付加価値化事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KANKOU-SAISEI', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', '観光地再生・高付加価値化事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KOKUSAI-KANKOU-ZEI', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', '国際観光旅客税活用事業（出国税活用） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SHUKUHAKU-BARRIERFREE', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', '宿泊施設バリアフリー化支援事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('WORKATION', 'https://www.mlit.go.jp/kankocho/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'ワーケーション等促進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('J-STARTUP', 'https://www.j-startup.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'J-Startup（スタートアップ育成プログラム） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('JIGYOU-HIKITSUGI', 'https://shoukei.smrj.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '事業承継・引継ぎ支援センター（無料相談） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KEIEI-SAFETY-KYOSAI', 'https://www.smrj.go.jp/kyosai/tkyosai/', 'not_found', 'monthly', 'needs_manual', 'not_found', '経営セーフティ共済（中小企業倒産防止共済制度） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('MICHIBIKI-RIYOU', 'https://qzss.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '準天頂衛星（みちびき）利活用推進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('MYNUMBER-RIKATSUYOU', 'https://www.digital.go.jp/policies/mynumber', 'not_found', 'monthly', 'needs_manual', 'not_found', 'マイナンバーカード利活用推進事業（公的個人認証基盤） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('NENNKIN-SEIKATSU', 'https://www.mhlw.go.jp/nenkinkyuufukin/', 'not_found', 'monthly', 'needs_manual', 'not_found', '年金生活者支援給付金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('NINSHIN-SOS', 'https://www.cfa.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '妊娠・出産包括支援事業（産後ケア等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('PPP-PFI', 'https://www8.cao.go.jp/pfi/pfi_jouhou/pfi_jouhou_index.html', 'not_found', 'monthly', 'needs_manual', 'not_found', 'PPP/PFI推進アクションプラン関連支援 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('RARE-METAL', 'https://www.jogmec.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'レアメタル等安定供給確保支援事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SHINKAI-KOUBUTSU', 'https://www.jogmec.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '深海底鉱物資源開発推進事業（レアアース泥等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('RE100-SUISHIN', 'https://www.env.go.jp/earth/', 'not_found', 'monthly', 'needs_manual', 'not_found', '再エネ電力利用拡大推進事業（RE100・再エネ100%電力調達） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('RITOU-KASSEI', 'https://www.mlit.go.jp/kokudoseisaku/chirit/kokudoseisaku_chirit_tk_000067.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '離島活性化交付金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('RITOU-SHINKOU', 'https://www.mlit.go.jp/kokudoseisaku/chirit/kokudoseisaku_chirit_tk_000027.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '離島活性化交付金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SAIGAI-SHIKIN-JFC', 'https://www.jfc.go.jp/n/finance/saftynet/', 'not_found', 'monthly', 'needs_manual', 'not_found', '災害復旧貸付（日本政策金融公庫・低利融資） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SAKOUJU', 'https://www.mlit.go.jp/jutakukentiku/house/jutakukentiku_house_tk3_000007.html', 'not_found', 'monthly', 'needs_manual', 'not_found', 'サービス付き高齢者向け住宅整備事業（サ高住補助金） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SBT-TCFD', 'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'SBT認定取得・TCFD提言に沿った情報開示支援 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SANGYOU-HOKEN-DANTAI', 'https://www.johas.go.jp/sangyouhoken/tabid/1999/Default.aspx', 'not_found', 'monthly', 'needs_manual', 'not_found', '団体経由産業保健活動推進助成金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SHIZEN-KOUEN', 'https://www.env.go.jp/nature/nationalparks/', 'not_found', 'monthly', 'needs_manual', 'not_found', '自然公園等整備事業（国立公園満喫プロジェクト等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SHIRITSU-SEIBI', 'https://www.mext.go.jp/a_menu/koutou/shinkou/', 'not_found', 'monthly', 'needs_manual', 'not_found', '私立学校施設整備費補助金（耐震・省エネ） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('RYOUSHI-INNOVATION', 'https://www.mext.go.jp/a_menu/shinkou/ryoushi/', 'not_found', 'monthly', 'needs_manual', 'not_found', '量子技術イノベーション拠点・産業利用推進事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('RYOUSHI-INNOVATION-2', 'https://www.mext.go.jp/a_menu/shinkou/ryoushi/', 'not_found', 'monthly', 'needs_manual', 'not_found', '量子技術イノベーション拠点形成事業（量子コンピュータ等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SHOUHISHA-KYOUIKU', 'https://www.caa.go.jp/policies/policy/consumer_education/', 'not_found', 'monthly', 'needs_manual', 'not_found', '消費者教育推進事業（高齢者・若年者の消費者被害防止） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SIP-PROGRAM', 'https://www8.cao.go.jp/cstp/gaiyo/sip/', 'not_found', 'monthly', 'needs_manual', 'not_found', '戦略的イノベーション創造プログラム（SIP）第3期 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SHOUKIBO-KYOSAI', 'https://www.smrj.go.jp/kyosai/skyosai/', 'not_found', 'monthly', 'needs_manual', 'not_found', '小規模企業共済（経営者のための退職金制度） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('TETSUDOU-BARRIERFREE', 'https://www.mlit.go.jp/tetudo/tetudo_fr1_000010.html', 'not_found', 'monthly', 'needs_manual', 'not_found', 'バリアフリー環境整備促進事業（鉄道駅エレベーター・ホームドア等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('TOSHI-SAISEI-SEIBI', 'https://www.mlit.go.jp/toshi/crd_machi_tk_000013.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '都市再生整備計画事業（まちづくり交付金） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SPORTS-SHISETSU', 'https://www.mext.go.jp/sports/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'スポーツ施設整備費補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('TOSHOKAN-DX', 'https://www.mext.go.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '図書館DX推進事業（電子書籍・デジタルアーカイブ等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('HIROSHIMA-MONO', 'https://www.pref.hiroshima.lg.jp/soshiki/', 'not_found', 'monthly', 'needs_manual', 'not_found', '広島県ものづくり革新支援補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('HOKKAIDO-ZERO-C', 'https://www.pref.hokkaido.lg.jp/kz/kke/', 'not_found', 'monthly', 'needs_manual', 'not_found', '北海道ゼロカーボン推進事業費補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('NIIGATA-SHOKEI', 'https://www.pref.niigata.lg.jp/sec/sangyoseisaku/', 'not_found', 'monthly', 'needs_manual', 'not_found', '新潟県事業承継支援補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('NIIGATA-IOTAI', 'https://www.pref.niigata.lg.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '新潟県IoT・AI推進補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('SAITAMA-SME', 'https://www.pref.saitama.lg.jp/a0803/', 'not_found', 'monthly', 'needs_manual', 'not_found', '埼玉県中小企業・スタートアップ支援（渋沢栄一起業家サロン等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('AICHI-STARTUP', 'https://aichi-startup.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'あいちスタートアップ戦略・PRE-STATION Ai 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('DENSHI-KARTE', 'https://iryohokenjyoho.service-now.com/csm', 'not_found', 'monthly', 'needs_manual', 'not_found', '医療情報化支援基金（電子カルテ標準化等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('EISEI-DATA', 'https://www.tellusxdp.com/', 'not_found', 'monthly', 'needs_manual', 'not_found', '衛星データ利活用促進事業（Tellus等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('FUKUOKA-STARTUP', 'https://growth-next.com/', 'not_found', 'monthly', 'needs_manual', 'not_found', '福岡スタートアップ支援（Fukuoka Growth Next・グローバル創業特区） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('FREELANCE-HOGO', 'https://freelance110.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', 'フリーランス事業者の取引適正化に関する相談・支援 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KAKAKU-TENKA', 'https://www.biz-partnership.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '価格転嫁対策支援事業（パートナーシップ構築宣言等） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KUMAMOTO-HANDOUTAI', 'https://www.pref.kumamoto.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '熊本県半導体関連企業支援補助金（TSMC関連） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KYUMIN-YOKIN', 'https://www.janpia.or.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '休眠預金等活用事業 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('KYOJU-SHIEN', 'https://www.safetynet-jutaku.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '住宅確保要配慮者居住支援事業（セーフティネット住宅） 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('NARA-BUNKA', 'https://www.pref.nara.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '奈良県文化財活用補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('OKAYAMA-DX-JINZAI', 'https://www.pref.okayama.jp/soshiki/list14.html', 'not_found', 'monthly', 'needs_manual', 'not_found', '岡山県デジタル人材育成補助金 公募要領 filetype:pdf', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO koubo_monitors (subsidy_id, koubo_page_url, pdf_source_method, crawl_schedule, status, last_crawl_result, fallback_search_query, created_at, updated_at) VALUES ('TOUSHI-IKUSEI', 'https://www.sbic.co.jp/', 'not_found', 'monthly', 'needs_manual', 'not_found', '中小企業投資育成株式会社制度 公募要領 filetype:pdf', datetime('now'), datetime('now'));