-- Manual deep crawl: koubo PDF URL updates
-- Generated: 2026-02-09

-- 千葉市テレワーク導入支援補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.city.chiba.jp/toshi/toshi/kotsu/documents/33_youkou190820.pdf", "PDF_source": "https://www.city.chiba.jp/keizainosei/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.city.chiba.jp/toshi/toshi/kotsu/documents/33_youkou190820.pdf", "https://www.city.chiba.jp/toshi/toshi/kotsu/documents/18_youkou.pdf", "https://www.city.chiba.jp/toshi/toshi/kotsu/documents/20_youkou.pdf", "https://www.city.chiba.jp/toshi/toshi/kotsu/documents/16_youkou.pdf", "https://www.city.chiba.jp/toshi/toshi/kotsu/documents/07_youkou.pdf"]}'), cached_at = datetime('now') WHERE id = 'CHIBA-TELEWORK';

-- 文化芸術振興費補助金（芸術文化活動支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "PDF_source": "https://www.bunka.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_01.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'BUNKA-SHINKOU';

-- 文化芸術振興費補助金（芸術文化活動支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "PDF_source": "https://www.bunka.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_01.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'BUNKAZAI-CHIIKI';

-- 文化芸術振興費補助金（芸術文化活動支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "PDF_source": "https://www.bunka.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_01.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'EIGA-SEISAKU';

-- 文化芸術振興費補助金（芸術文化活動支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "PDF_source": "https://www.bunka.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_01.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'KOKUSAI-BUNKA';

-- 文化芸術振興費補助金（芸術文化活動支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "PDF_source": "https://www.bunka.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_02.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_01.pdf", "https://www.bunka.go.jp/shinsei_boshu/saiyo/pdf/94326201_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_03.pdf", "https://www.bunka.go.jp/shinsei_boshu/kobo/pdf/94325501_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'MEDIA-GEIJUTSU';

-- 工場・事業場における先導的脱炭素化推進事業（SHIFT事業）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://shift.env.go.jp/files/navi/guideline/2016potential_guideline.pdf", "PDF_source": "https://shift.env.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://shift.env.go.jp/files/navi/guideline/2016potential_guideline.pdf", "https://shift.env.go.jp/files/navi/guideline/2016guideline.pdf", "https://www.gaj.or.jp/eie/shift/koubo/document/R6/O/sf06Ho5.pdf", "https://www.gaj.or.jp/eie/shift/koubo/document/R6/A/sf06Ha5.pdf", "https://www.gaj.or.jp/eie/shift/koubo/document/R6/O/sf06Ho6.pdf"]}'), cached_at = datetime('now') WHERE id = 'DATSUTANSO-SENDOU';

-- GovTech推進事業（行政DXスタートアップ支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e98a2d2e-f6da-4dce-a3c3-360a38616d8d/3389425f/20251104_procurement_guideline_01.pdf", "PDF_source": "https://www.digital.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e98a2d2e-f6da-4dce-a3c3-360a38616d8d/3389425f/20251104_procurement_guideline_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'GOVTECH-SUISHIN';

-- GovTech推進事業（行政DXスタートアップ支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e98a2d2e-f6da-4dce-a3c3-360a38616d8d/3389425f/20251104_procurement_guideline_01.pdf", "PDF_source": "https://www.digital.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e98a2d2e-f6da-4dce-a3c3-360a38616d8d/3389425f/20251104_procurement_guideline_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'MYNA-PORTAL-BIZ';

-- GovTech推進事業（行政DXスタートアップ支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e98a2d2e-f6da-4dce-a3c3-360a38616d8d/3389425f/20251104_procurement_guideline_01.pdf", "PDF_source": "https://www.digital.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e98a2d2e-f6da-4dce-a3c3-360a38616d8d/3389425f/20251104_procurement_guideline_01.pdf"]}'), cached_at = datetime('now') WHERE id = 'NOUFU-SHOUMEI';

-- 漁業構造改革総合対策事業（省エネ機器導入）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "PDF_source": "https://www.jfa.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-6.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-2.pdf"]}'), cached_at = datetime('now') WHERE id = 'GYOGYOU-SHOUENE';

-- 漁業構造改革総合対策事業（省エネ機器導入）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "PDF_source": "https://www.jfa.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-6.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-2.pdf"]}'), cached_at = datetime('now') WHERE id = 'GYOKOU-SEIBI';

-- 漁業構造改革総合対策事業（省エネ機器導入）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "PDF_source": "https://www.jfa.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-6.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-2.pdf"]}'), cached_at = datetime('now') WHERE id = 'SUISAN-KAKOU';

-- 漁業構造改革総合対策事業（省エネ機器導入）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "PDF_source": "https://www.jfa.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-6.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-2.pdf"]}'), cached_at = datetime('now') WHERE id = 'SUISAN-KYOUSOU';

-- 漁業構造改革総合対策事業（省エネ機器導入）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "PDF_source": "https://www.jfa.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-13.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-6.pdf", "https://www.jfa.maff.go.jp/j/kakou/attach/pdf/suisann-kensa-koubo-2.pdf"]}'), cached_at = datetime('now') WHERE id = 'YOUSHOKU-SEICHOU';

-- 浜松市産業イノベーション補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.city.hamamatsu.shizuoka.jp/documents/90205/youkou2.pdf", "PDF_source": "https://www.city.hamamatsu.shizuoka.jp/sangyo/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.city.hamamatsu.shizuoka.jp/documents/90205/youkou2.pdf", "https://www.city.hamamatsu.shizuoka.jp/documents/90205/monita-teianbosyuyoukou.pdf", "https://www.city.hamamatsu.shizuoka.jp/documents/90205/r7_gomibenrityouyouryou.pdf", "https://www.city.hamamatsu.shizuoka.jp/documents/90205/r6youryou.pdf", "https://www.city.hamamatsu.shizuoka.jp/documents/90205/shiminongakuho-ru_boshuyoukou.pdf"]}'), cached_at = datetime('now') WHERE id = 'HAMAMATSU-INNOV';

-- 茨城県イノベーション推進補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.pref.ibaraki.jp/bugai/koho/kenmin/ad/documents/20200401youkou.pdf", "PDF_source": "https://www.pref.ibaraki.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.pref.ibaraki.jp/bugai/koho/kenmin/ad/documents/20200401youkou.pdf"]}'), cached_at = datetime('now') WHERE id = 'IBARAKI-INNOV';

-- 石川県伝統工芸イノベーション補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.pref.ishikawa.lg.jp/kouhou/fukaboushi/documents/01_00_zisshiyouryou.pdf", "PDF_source": "https://www.pref.ishikawa.lg.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.pref.ishikawa.lg.jp/kouhou/fukaboushi/documents/01_00_zisshiyouryou.pdf"]}'), cached_at = datetime('now') WHERE id = 'ISHIKAWA-DENTOU';

-- 人材確保等支援助成金（中小企業団体助成コース）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf", "PDF_source": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000199292.html", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf"]}'), cached_at = datetime('now') WHERE id = 'JINZAI-KAKUHO-DANTAI';

-- 人材確保等支援助成金（中小企業団体助成コース）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf", "PDF_source": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000199292.html", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf"]}'), cached_at = datetime('now') WHERE id = 'JINZAI-KAKUHO-KANRI';

-- 人材確保等支援助成金（中小企業団体助成コース）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf", "PDF_source": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000199292.html", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf"]}'), cached_at = datetime('now') WHERE id = 'JINZAI-KAKUHO-KENSETSU';

-- 介護職員処遇改善支援補助金（賃上げ支援）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf", "PDF_source": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.mhlw.go.jp/shinsei_boshu/denshishinesei/dl/h241108_2.pdf"]}'), cached_at = datetime('now') WHERE id = 'KAIGO-SYOKUGYOU';

-- 海外展開・事業再編資金（中小企業の海外進出支援融資）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou02.pdf", "PDF_source": "https://www.jfc.go.jp/n/finance/search/kaigaitenkai.html", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou02.pdf", "https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou01.pdf"]}'), cached_at = datetime('now') WHERE id = 'KAIGAI-YUSHI';

-- 科学研究費助成事業（基盤研究C）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jsps.go.jp/file/storage/kaken_tokus2025/r8_4_koubotsuchi.pdf", "PDF_source": "https://www.jsps.go.jp/j-grantsinaid/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jsps.go.jp/file/storage/kaken_tokus2025/r8_4_koubotsuchi.pdf", "https://www.jsps.go.jp/file/storage/kaken_kiban_2025_g_3687/r8_7_koubotsuchi.pdf", "https://www.jsps.go.jp/file/storage/kaken_11_g_3698/r8_youryou_web.pdf", "https://www.jsps.go.jp/file/storage/kaken_11_g_3698/r8_youryou_tenpu.pdf", "https://www.jsps.go.jp/file/storage/kaken_11_g_3698/r8_koubo_shourei.pdf"]}'), cached_at = datetime('now') WHERE id = 'KAKENHI-KIBAN-C';

-- 科学研究費助成事業（基盤研究C）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jsps.go.jp/file/storage/kaken_tokus2025/r8_4_koubotsuchi.pdf", "PDF_source": "https://www.jsps.go.jp/j-grantsinaid/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jsps.go.jp/file/storage/kaken_tokus2025/r8_4_koubotsuchi.pdf", "https://www.jsps.go.jp/file/storage/kaken_kiban_2025_g_3687/r8_7_koubotsuchi.pdf", "https://www.jsps.go.jp/file/storage/kaken_11_g_3698/r8_youryou_web.pdf", "https://www.jsps.go.jp/file/storage/kaken_11_g_3698/r8_youryou_tenpu.pdf", "https://www.jsps.go.jp/file/storage/kaken_11_g_3698/r8_koubo_shourei.pdf"]}'), cached_at = datetime('now') WHERE id = 'KAKENHI-WAKATE';

-- 中小企業経営力強化資金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou02.pdf", "PDF_source": "https://www.jfc.go.jp/n/finance/search/64.html", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou02.pdf", "https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou01.pdf"]}'), cached_at = datetime('now') WHERE id = 'KEIEI-KYOUKA-YUSHI';

-- マル経融資（小規模事業者経営改善資金融資制度）
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou02.pdf", "PDF_source": "https://www.jfc.go.jp/n/finance/search/kaizen_m.html", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou02.pdf", "https://www.jfc.go.jp/n/sabekai/pdf/taiouyouryou01.pdf"]}'), cached_at = datetime('now') WHERE id = 'MARUKEI-YUSHI';

-- 宮城県中小企業DX推進補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.pref.miyagi.jp/documents/63144/01_r8snsbosyuyouryou.pdf", "PDF_source": "https://www.pref.miyagi.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.pref.miyagi.jp/documents/63144/01_r8snsbosyuyouryou.pdf", "https://www.pref.miyagi.jp/documents/63213/bosyuuyouryou.pdf", "https://zero-carbon2050.pref.miyagi.jp/wp-content/uploads/2025/02/memboshu-leaf.pdf", "https://zero-carbon2050.pref.miyagi.jp/wp-content/uploads/2024/12/zero_youkou_240419.pdf"]}'), cached_at = datetime('now') WHERE id = 'MIYAGI-DX';

-- 宮城県中小企業DX推進補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.pref.miyagi.jp/documents/63144/01_r8snsbosyuyouryou.pdf", "PDF_source": "https://www.pref.miyagi.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.pref.miyagi.jp/documents/63144/01_r8snsbosyuyouryou.pdf", "https://www.pref.miyagi.jp/documents/63213/bosyuuyouryou.pdf", "https://zero-carbon2050.pref.miyagi.jp/wp-content/uploads/2025/02/memboshu-leaf.pdf", "https://zero-carbon2050.pref.miyagi.jp/wp-content/uploads/2024/12/zero_youkou_240419.pdf"]}'), cached_at = datetime('now') WHERE id = 'MIYAGI-SHINSANGYOU';

-- 長野県DX推進モデル事業補助金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.pref.nagano.lg.jp/koho/sangyo/shokogyo/banner/documents/banneryouryou.pdf", "PDF_source": "https://www.pref.nagano.lg.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.pref.nagano.lg.jp/koho/sangyo/shokogyo/banner/documents/banneryouryou.pdf", "https://www.pref.nagano.lg.jp/koho/sangyo/shokogyo/banner/documents/homepage_youkou_20230401.pdf"]}'), cached_at = datetime('now') WHERE id = 'NAGANO-DX';

-- 横浜市中小企業設備投資助成金
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"公募要領PDF_URL": "https://www.city.yokohama.lg.jp/business/kigyoshien/chuoshijo/kaisei_ikenkoubo.files/kaiseigaiyo.pdf", "PDF_source": "https://www.city.yokohama.lg.jp/business/kigyoshien/", "PDF_verified_at": "2026-02-09", "PDF_method": "sub_page", "all_koubo_pdfs": ["https://www.city.yokohama.lg.jp/business/kigyoshien/chuoshijo/kaisei_ikenkoubo.files/kaiseigaiyo.pdf", "https://www.city.yokohama.lg.jp/business/kigyoshien/chuoshijo/kaisei_ikenkoubo.files/kouboyoruryo.pdf"]}'), cached_at = datetime('now') WHERE id = 'YOKOHAMA-SETSUBI';

-- Related PDFs (no koubo keyword match)
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.nedo.go.jp/content/800048122.pdf", "https://www.nedo.go.jp/content/800048124.pdf", "https://www.nedo.go.jp/content/800048126.pdf", "https://www.nedo.go.jp/content/800048123.pdf", "https://www.nedo.go.jp/content/800046841.pdf"], "PDF_source": "https://www.nedo.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'CARBON-RECYCLE';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.nedo.go.jp/content/800048122.pdf", "https://www.nedo.go.jp/content/800048124.pdf", "https://www.nedo.go.jp/content/800048126.pdf", "https://www.nedo.go.jp/content/800048123.pdf", "https://www.nedo.go.jp/content/800046841.pdf"], "PDF_source": "https://www.nedo.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'NEDO-RD';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.nedo.go.jp/content/800048122.pdf", "https://www.nedo.go.jp/content/800048124.pdf", "https://www.nedo.go.jp/content/800048126.pdf", "https://www.nedo.go.jp/content/800048123.pdf", "https://www.nedo.go.jp/content/800046841.pdf"], "PDF_source": "https://www.nedo.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'PEROVSKITE-JISSHOU';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.soumu.go.jp/menu_sinsei/shinsei/pdf/060427_1.pdf"], "PDF_source": "https://www.soumu.go.jp/main_sosiki/jichi_gyousei/c-gyousei/02gyosei08_03000066.html", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'CHIIKI-OKOSHI';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-32.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-14.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-29.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-7.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-44.pdf"], "PDF_source": "https://www.rinya.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'CLT-MOKUZAI';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-32.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-14.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-29.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-7.pdf", "https://www.rinya.maff.go.jp/j/mokusan/rinyahp/attach/pdf/20251001-1-44.pdf"], "PDF_source": "https://www.rinya.maff.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'SHINRIN-SAISEI';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.pref.gunma.jp/uploaded/attachment/688853.pdf", "https://www.pref.gunma.jp/uploaded/attachment/687584.pdf"], "PDF_source": "https://www.pref.gunma.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'GUNMA-SOUGYOU';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.env.go.jp/recycle/jokaso/grant/pdf/r041202_jisshinituite.pdf", "https://www.env.go.jp/recycle/jokaso/grant/pdf/r070513_kokyo_yoko.pdf", "https://www.env.go.jp/recycle/jokaso/grant/pdf/r060319_jisshinituite.pdf", "https://www.env.go.jp/recycle/jokaso/grant/pdf/r070513_yokokaisei.pdf", "https://www.env.go.jp/recycle/jokaso/grant/pdf/guiding_principle.pdf"], "PDF_source": "https://www.env.go.jp/recycle/jokaso/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'JOUKASOU-SEIBI';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.houterasu.or.jp/uploaded/attachment/7213.pdf", "https://www.houterasu.or.jp/uploaded/attachment/7059.pdf", "https://www.houterasu.or.jp/uploaded/attachment/7149.pdf", "https://www.houterasu.or.jp/uploaded/attachment/7211.pdf", "https://www.houterasu.or.jp/uploaded/attachment/7162.pdf"], "PDF_source": "https://www.houterasu.or.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'JINKEN-SOUDAN';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.pref.kagoshima.jp/ag25/documents/34802_20250905104418-1.pdf", "https://www.pref.kagoshima.jp/ag25/documents/34802_20250627175653-1.pdf", "https://www.pref.kagoshima.jp/ag25/documents/34802_20250715130429-1.pdf", "https://www.pref.kagoshima.jp/ag25/documents/34802_20250214130636-1.pdf", "https://www.pref.kagoshima.jp/ag25/documents/34802_20260205144609-1.pdf"], "PDF_source": "https://www.pref.kagoshima.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'KAGOSHIMA-NOUGYOU';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://kenko-keiei.jp/wp-content/uploads/2025/10/Chusho_QA20251008.pdf", "https://kenko-keiei.jp/wp-content/themes/kenko_keiei_cms/files/r6schedule.pdf", "https://kenko-keiei.jp/wp-content/uploads/2025/08/20250818paymentFAQ.pdf", "https://kenko-keiei.jp/wp-content/uploads/2025/09/Dai_QA20250919.pdf", "https://kenko-keiei.jp/wp-content/themes/kenko_keiei_cms/files/kk2026sample_chu.pdf"], "PDF_source": "https://kenko-keiei.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'KENKOU-KEIEI';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://saiyo-nagasaki.jinjii.jp/wp-content/uploads/2024/01/t_saiyou2025.pdf", "https://saiyo-nagasaki.jinjii.jp/wp-content/uploads/2024/01/saiyou2025.pdf"], "PDF_source": "https://www.pref.nagasaki.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'NAGASAKI-ZOSEN';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.pref.okinawa.jp/_res/projects/default_project/_page_/001/038/260/kikaku.pdf", "https://www.pref.okinawa.jp/_res/projects/default_project/_page_/001/038/260/yoiusiki-pdf.pdf", "https://www.pref.okinawa.jp/_res/projects/default_project/_page_/001/038/260/keiyakusho.pdf", "https://www.pref.okinawa.jp/_res/projects/default_project/_page_/001/038/260/qar080209.pdf", "https://www.pref.okinawa.jp/_res/projects/default_project/_page_/001/038/260/siyousho.pdf"], "PDF_source": "https://www.pref.okinawa.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'OKINAWA-ICT';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.pref.oita.jp/uploaded/life/2327703_4659995_misc.pdf", "https://www.pref.oita.jp/uploaded/life/2327703_4660001_misc.pdf", "https://www.pref.oita.jp/uploaded/life/2327703_4659994_misc.pdf"], "PDF_source": "https://www.pref.oita.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'OITA-ONSEN';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.johas.go.jp/Portals/0/data0/jigyogaiyo/choutatsu/kaigou/0707/giteisyo_kouhyou070722.pdf", "https://www.johas.go.jp/Portals/0/data0/jigyogaiyo/choutatsu/kaigou/0506/kaigou050614.pdf", "https://www.johas.go.jp/Portals/0/data0/jigyogaiyo/choutatsu/kaigou/0705/kaigou070526.pdf", "https://www.johas.go.jp/Portals/0/data0/jigyogaiyo/choutatsu/kaigou/0405/kaigou040527.pdf", "https://www.johas.go.jp/Portals/0/data0/jigyogaiyo/choutatsu/kaigou/0305/kaigou030520(1).pdf"], "PDF_source": "https://www.johas.go.jp/shisetsu/tabid/578/Default.aspx", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'SANGYOU-HOKEN-SOUGOU';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://telework.mhlw.go.jp/kagayakutelework/seminar/pdf/telework_seminar_2025_1218.pdf", "https://telework.mhlw.go.jp/kagayakutelework/seminar/pdf/proceedings_2025_1218.pdf?251121", "https://telework.mhlw.go.jp/kagayakutelework/seminar/2025/pdf/1218/file02.pdf", "https://telework.mhlw.go.jp/kagayakutelework/seminar/2025/pdf/1218/file04.pdf", "https://telework.mhlw.go.jp/kagayakutelework/seminar/2025/pdf/1218/file01.pdf"], "PDF_source": "https://telework.mhlw.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'TELEWORK-MHLW';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.pref.toyama.jp/documents/31897/r8_kurobe.pdf", "https://www.pref.toyama.jp/documents/32045/r8bosyuu.pdf"], "PDF_source": "https://www.pref.toyama.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'TOYAMA-MONO';
UPDATE subsidy_cache SET detail_json = json_patch(COALESCE(detail_json, '{}'), '{"関連PDF_URL": ["https://www.mext.go.jp/sports/content/250515-spt_kensport01-000042499_07.pdf", "https://sportinlife.go.jp/wp-content/themes/release/assets/images/page-offer/pdf/2025-pdf/offer_participant2025.pdf", "https://www.mext.go.jp/sports/content/250515-spt_kensport01-000042499_03.pdf", "https://www.mext.go.jp/sports/content/20250305-spt_sseisaku02-000040740_110.pdf"], "PDF_source": "https://sportinlife.go.jp/", "PDF_verified_at": "2026-02-09", "PDF_method": "related_deep_crawl"}'), cached_at = datetime('now') WHERE id = 'UNDOU-SHUUKANKA';